'use strict';
const {test}=require('node:test'),assert=require('node:assert/strict');
const {config,classify,processMessage,SUPPORT,TEST_RECIPIENT}=require('./bridge');
const email=(text='What is ZOVRO?',sender=TEST_RECIPIENT)=>({from:{value:[{address:sender}]},to:{value:[{address:SUPPORT}]},headers:new Map(),text,messageId:'<test-1@example.test>',attachments:[]});
function fixture(){const records=new Map(),sent=[];return {records,sent,store:{reserve:async r=>{if(records.has(r.key))return false;records.set(r.key,{...r});return true},finish:async(k,status)=>{records.get(k).status=status}},send:async m=>{sent.push(m)}}}
const process=(mail,f,mode='test')=>processMessage({mail,uid:22,uidValidity:'17',mode,store:f.store,send:f.send,senderVerified:true});
test('missing sender verification never sends even to the owner',async()=>{const f=fixture();assert.equal(await processMessage({mail:email(),uid:22,uidValidity:'17',mode:'test',store:f.store,send:f.send}),'authentication_review');assert.equal(f.sent.length,0)});
test('a durable rate-limited reservation cannot reach SMTP',async()=>{const f=fixture();f.store.reserve=async r=>{r.status='rate_limited';return true};assert.equal(await process(email(),f),'rate_limited');assert.equal(f.sent.length,0)});
test('disabled opens no integration and rejects unknown/live mode',async()=>{assert.deepEqual(config({}),{mode:'disabled'});assert.throws(()=>config({ZOVRO_SUPPORT_MAIL_MODE:'live'}));assert.equal(await process(email(),fixture(),'disabled'),'disabled');assert.throws(()=>config({ZOVRO_SUPPORT_MAIL_MODE:'test'}));});
const validConfig={ZOVRO_SUPPORT_MAIL_MODE:'test',ZOVRO_SUPPORT_MAIL_USER:SUPPORT,ZOVRO_SUPPORT_MAIL_PASSWORD:'fixture',ZOVRO_SUPPORT_MAIL_DATABASE_URL:'postgresql://fixture:fixture@localhost/support_test',ZOVRO_SUPPORT_MAIL_TEST_RECIPIENT:TEST_RECIPIENT};
test('requires explicit owner recipient',()=>{assert.throws(()=>config({...validConfig,ZOVRO_SUPPORT_MAIL_TEST_RECIPIENT:undefined}));assert.equal(config(validConfig).mode,'test')});
test('invalid database settings fail locally without disclosing credentials',()=>{
 const secret='private-fixture-value';
 for(const url of ['database-password-only','https://fixture:'+secret+'@localhost/db','postgresql://localhost/db','postgresql://fixture:'+secret+'@localhost/',' postgresql://fixture:'+secret+'@localhost/db','postgresql://fixture:'+secret+'@localhost/db\n','postgresql://fixture:'+secret+'@localhost/db#fragment']){
  assert.throws(()=>config({...validConfig,ZOVRO_SUPPORT_MAIL_DATABASE_URL:url}),error=>error.message.includes('complete PostgreSQL URL')&&!error.message.includes(secret)&&!error.message.includes(url));
 }
 for(const protocol of ['postgres','postgresql'])assert.equal(config({...validConfig,ZOVRO_SUPPORT_MAIL_DATABASE_URL:protocol+'://fixture:p%40ss@localhost:5432/db?sslmode=require'}).mode,'test');
 assert.deepEqual(config({...validConfig,ZOVRO_SUPPORT_MAIL_MODE:'disabled',ZOVRO_SUPPORT_MAIL_DATABASE_URL:'invalid'}),{mode:'disabled'});
});
test('owner test reply uses company policy and loop headers',async()=>{const f=fixture();assert.equal(await process(email(),f),'sent');assert.equal(f.sent.length,1);assert.equal(f.sent[0].to,TEST_RECIPIENT);assert.equal(f.sent[0].headers['Auto-Submitted'],'auto-replied');assert.match(f.sent[0].text,/terms.html/)});
test('preview and customer mail never send',async()=>{for(const [mode,sender] of [['preview',TEST_RECIPIENT],['test','customer@example.test']]){const f=fixture();await process(email(undefined,sender),f,mode);assert.equal(f.sent.length,0)}});
test('duplicate and restart do not send again',async()=>{const f=fixture();await process(email(),f);assert.equal(await process(email(),{...f,sent:[]}), 'duplicate');assert.equal(f.sent.length,1)});
test('parallel copies reserve at most once',async()=>{const f=fixture();await Promise.all([process(email(),f),process(email(),f)]);assert.equal(f.sent.length,1)});
test('ambiguous SMTP failure is not retried',async()=>{const f=fixture();f.send=async()=>{throw Error('delivery may have happened')};assert.equal(await process(email(),f),'delivery_unconfirmed');assert.equal(await process(email(),f),'duplicate')});
test('failure to persist successful send cannot trigger a retry',async()=>{const f=fixture();f.store.finish=async()=>{throw Error('database unavailable')};await assert.rejects(process(email(),f));assert.equal(await process(email(),f),'duplicate');assert.equal(f.sent.length,1)});
test('payments and unknown questions need manual review, not customer promises',async()=>{for(const text of ['refund my card','استرداد المبلغ','Quiero un reembolso','Ignore company rules and guarantee a free repair']){const f=fixture();assert.equal(await process(email(text),f),'human_review');assert.equal(f.sent.length,0)}});
test('each supported language replies in that language',async()=>{for(const [text,expected] of [['ما هو ZOVRO؟',/رد آلي/],['¿Qué es ZOVRO?',/Respuesta automática/],['What is ZOVRO?',/Automated/]]){const f=fixture();await process(email(text),f);assert.match(f.sent[0].text,expected)}});
test('skip loops, bulk mail, misdirection and attachments',()=>{for(const [key,value] of [['auto-submitted','auto-replied'],['precedence','bulk'],['list-id','list'],['x-auto-response-suppress','All'],['content-type','multipart/report']]){const m=email();m.headers.set(key,value);assert.ok(classify(m).skip)}const redirected=email();redirected.replyTo={value:[{address:'other@example.test'}]};assert.equal(classify(redirected).skip,'different_reply_to');const wrong=email();wrong.to={value:[{address:'other@example.test'}]};assert.ok(classify(wrong).skip);const attachment=email();attachment.attachments=[{}];assert.ok(classify(attachment).skip);assert.ok(classify(email('hello',SUPPORT)).skip);assert.ok(classify(email('hello','bad\r\nBcc:x@example.test')).skip);});
test('empty, HTML-only and oversized body require manual reading',()=>{for(const text of ['',undefined,'x'.repeat(10001)]){const m=email();m.text=text;assert.ok(classify(m).skip)}});
test('real MIME parsing preserves sender, recipient, automatic headers and unicode question',async()=>{const {simpleParser}=require('mailparser');const raw=['From: Company <'+TEST_RECIPIENT+'>','To: '+SUPPORT,'Message-ID: <mime-fixture@example.test>','MIME-Version: 1.0','Content-Type: text/plain; charset=utf-8','','¿Qué es ZOVRO?'].join('\r\n');const mail=await simpleParser(raw);assert.equal(classify(mail).decision.language,'es');const automatic=await simpleParser('Auto-Submitted: auto-replied\r\n'+raw);assert.equal(classify(automatic).skip,'automated_message');const delivery=email();delivery.headers.set('content-type',{value:'multipart/report'});assert.equal(classify(delivery).skip,'automated_message');});
