(function(){
'use strict';
const KEY='zovroLanguage';
const exact={'Home':'Inicio','Jobs':'Trabajos','Nearby':'Cercanos','Profile':'Perfil','Popular services':'Servicios populares','Your ZOVRO account':'Tu cuenta ZOVRO','Get started':'Comenzar','SOS Roadside':'SOS carretera','Trusted providers':'Proveedores confiables','Nearby help':'Ayuda cercana','Fast response':'Respuesta rápida','New request':'Nueva solicitud','Refresh':'Actualizar','Available':'Disponible','Share location':'Compartir ubicación','Use my location':'Usar mi ubicación','Profile & Security':'Perfil y seguridad','Sign out':'Cerrar sesión','Delete account':'Eliminar cuenta','Legal & Support':'Legal y soporte','Privacy Policy':'Política de privacidad','Terms':'Términos','Support':'Soporte','Sign in':'Iniciar sesión','Create account':'Crear cuenta','Phone':'Teléfono','Password':'Contraseña','Continue':'Continuar','Cancel':'Cancelar','Request a service':'Solicitar un servicio','Service':'Servicio','Details':'Detalles','Address / landmark':'Dirección / punto de referencia','Urgent request':'Solicitud urgente','Submit request':'Enviar solicitud','Accepted':'Aceptado','On the way':'En camino','Arrived':'Llegó','In progress':'En progreso','Completed':'Completado','Cancelled':'Cancelado','Looking for providers':'Buscando proveedores','Send':'Enviar','Close':'Cerrar','Roadside Assistance':'Asistencia en carretera','Mobile Mechanic':'Mecánico móvil','HVAC':'Climatización','Plumbing':'Plomería','Electrical':'Electricidad','Appliance Repair':'Reparación de electrodomésticos','Roofing':'Techos','Painting':'Pintura','Flooring':'Pisos','Lawn Care':'Jardinería','Snow Removal':'Remoción de nieve','Debris Cleanup':'Retiro de escombros','Light Moving':'Mudanza ligera'};
const ar={'Home':'الرئيسية','Jobs':'الطلبات','Nearby':'بالقرب منك','Profile':'الملف الشخصي','Popular services':'الخدمات الشائعة','Your ZOVRO account':'حساب ZOVRO','Get started':'ابدأ','SOS Roadside':'طوارئ الطريق','Trusted providers':'مهنيون موثوقون','Nearby help':'مساعدة قريبة','Fast response':'استجابة سريعة','New request':'طلب جديد','Refresh':'تحديث','Available':'متاح','Share location':'مشاركة الموقع','Use my location':'استخدام موقعي','Profile & Security':'الملف الشخصي والأمان','Sign out':'تسجيل الخروج','Delete account':'حذف الحساب','Legal & Support':'القانون والدعم','Privacy Policy':'سياسة الخصوصية','Terms':'الشروط','Support':'الدعم','Sign in':'تسجيل الدخول','Create account':'إنشاء حساب','Phone':'الهاتف','Password':'كلمة المرور','Continue':'متابعة','Cancel':'إلغاء','Request a service':'طلب خدمة','Service':'الخدمة','Details':'التفاصيل','Address / landmark':'العنوان / علامة مميزة','Urgent request':'طلب عاجل','Submit request':'إرسال الطلب','Accepted':'تم القبول','On the way':'في الطريق','Arrived':'وصل','In progress':'العمل جارٍ','Completed':'مكتمل','Cancelled':'ملغي','Looking for providers':'البحث عن مهنيين','Send':'إرسال','Close':'إغلاق','Roadside Assistance':'مساعدة على الطريق','Mobile Mechanic':'ميكانيكي متنقل','HVAC':'تدفئة وتبريد','Plumbing':'سباكة','Electrical':'كهرباء','Appliance Repair':'إصلاح الأجهزة','Roofing':'أسقف','Painting':'دهان','Flooring':'أرضيات','Lawn Care':'العناية بالحدائق','Snow Removal':'إزالة الثلوج','Debris Cleanup':'إزالة المخلفات','Light Moving':'نقل خفيف'};
const placeholders={'Describe what you need':'Describe lo que necesitas','Optional':'Opcional','10+ characters, letters and numbers':'10+ caracteres, letras y números'};
function lang(){const saved=localStorage.getItem(KEY);if(saved)return saved;const n=(navigator.language||'en').toLowerCase();return n.startsWith('ar')?'ar':n.startsWith('es')?'es':'en'}
function mapText(s){const l=lang();if(l==='en')return s;const lead=s.match(/^\s*/)?.[0]||'',trail=s.match(/\s*$/)?.[0]||'',core=s.trim(),dict=l==='ar'?ar:exact;return lead+(dict[core]||core)+trail}
function apply(root=document){document.documentElement.lang=lang();document.documentElement.dir=lang()==='ar'?'rtl':'ltr';const walker=document.createTreeWalker(root,NodeFilter.SHOW_TEXT,{acceptNode:n=>{const p=n.parentElement;if(!p||['SCRIPT','STYLE','TEXTAREA'].includes(p.tagName))return NodeFilter.FILTER_REJECT;return n.nodeValue.trim()?NodeFilter.FILTER_ACCEPT:NodeFilter.FILTER_REJECT}});const nodes=[];while(walker.nextNode())nodes.push(walker.currentNode);for(const n of nodes){if(!n.__zovroEn)n.__zovroEn=n.nodeValue;n.nodeValue=lang()==='en'?n.__zovroEn:mapText(n.__zovroEn)}root.querySelectorAll?.('input[placeholder],textarea[placeholder]').forEach(el=>{if(!el.dataset.zovroPlaceholderEn)el.dataset.zovroPlaceholderEn=el.getAttribute('placeholder')||'';const en=el.dataset.zovroPlaceholderEn;el.setAttribute('placeholder',lang()==='es'?(placeholders[en]||en):en)});const sel=document.getElementById('zovroLanguage');if(sel)sel.value=lang()}
let timer;const observer=new MutationObserver(()=>{clearTimeout(timer);timer=setTimeout(()=>apply(document.body),0)});
function setLanguage(v){localStorage.setItem(KEY,['en','es','ar'].includes(v)?v:'en');apply(document.body)}
window.ZOVRO_I18N={getLanguage:lang,setLanguage,apply};document.addEventListener('DOMContentLoaded',()=>{apply(document.body);observer.observe(document.body,{childList:true,subtree:true})});
})();
