'use strict';
(function(){
const state={nearbyMap:null,jobMap:null,nearbyMarker:null,customerMarker:null,providerMarker:null,route:null,jobId:null,timer:null,lastNearby:null};
function ensureCss(){if(document.getElementById('zovro-live-map-style'))return;const s=document.createElement('style');s.id='zovro-live-map-style';s.textContent='.zmap-card{margin-top:12px}.zmap{height:320px;border-radius:18px;overflow:hidden;border:1px solid var(--line);background:#eef2f7}.zmap-meta{display:flex;gap:10px;flex-wrap:wrap;margin:10px 0}.zmap-pill{padding:7px 10px;border-radius:999px;background:#eef2f7;font-size:12px;font-weight:800}.zmap-note{font-size:12px;color:var(--muted)}';document.head.appendChild(s)}
function inject(){ensureCss();const near=document.getElementById('nearby'),jobs=document.getElementById('jobs');if(near&&!document.getElementById('nearbyMapCard')){const d=document.createElement('div');d.id='nearbyMapCard';d.className='card zmap-card';d.innerHTML='<b>Nearby map</b><p class="zmap-note">Your exact location is shown. Provider exact locations remain private until a job is accepted.</p><div id="nearbyMap" class="zmap"></div><div id="nearbyMapMeta" class="zmap-meta"></div>';near.insertBefore(d,document.getElementById('nearbyList'))}if(jobs&&!document.getElementById('jobMapCard')){const d=document.createElement('div');d.id='jobMapCard';d.className='card zmap-card hidden';d.innerHTML='<div class="row"><div class="grow"><b>Live job tracking</b><div class="zmap-note">Provider location updates automatically while the job is active.</div></div><button id="zovroNavigate" class="btn ghost hidden">Navigate</button></div><div id="jobMap" class="zmap"></div><div id="jobMapMeta" class="zmap-meta"></div>';jobs.insertBefore(d,document.getElementById('jobList'))}}
function loadLeaflet(){if(window.L)return Promise.resolve();return new Promise((resolve,reject)=>{const css=document.createElement('link');css.rel='stylesheet';css.href='https://unpkg.com/leaflet@1.9.4/dist/leaflet.css';css.integrity='sha256-p4NxAoJBhIINfQ3ynY5P+9WjYv6q3Zr0h3fYQ8Qqj4k=';css.crossOrigin='';document.head.appendChild(css);const sc=document.createElement('script');sc.src='https://unpkg.com/leaflet@1.9.4/dist/leaflet.js';sc.integrity='sha256-20nQCchB9co0qIjJZRGuk2/Z9VM+kNiyxNV1lvTlZBo=';sc.crossOrigin='';sc.onload=resolve;sc.onerror=()=>reject(Error('Map library unavailable'));document.head.appendChild(sc)})}
function baseMap(id,center){const m=L.map(id,{zoomControl:true,attributionControl:true}).setView(center,12);L.tileLayer('https://tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:19,attribution:'© OpenStreetMap contributors'}).addTo(m);return m}
function distMiles(a,b){if(!a||!b)return null;const r=x=>x*Math.PI/180,R=3958.8,d1=r(b.lat-a.lat),d2=r(b.lng-a.lng),q=Math.sin(d1/2)**2+Math.cos(r(a.lat))*Math.cos(r(b.lat))*Math.sin(d2/2)**2;return 2*R*Math.asin(Math.sqrt(q))}
function eta(d){return d==null?null:Math.max(5,Math.round(d*3+5))}
async function renderNearby(pos,providers=[],radius=25){inject();state.lastNearby=pos;await loadLeaflet();if(!state.nearbyMap)state.nearbyMap=baseMap('nearbyMap',[pos.lat,pos.lng]);state.nearbyMap.setView([pos.lat,pos.lng],11);if(state.nearbyMarker)state.nearbyMarker.remove();state.nearbyMarker=L.marker([pos.lat,pos.lng]).addTo(state.nearbyMap).bindPopup('You are here');L.circle([pos.lat,pos.lng],{radius:radius*1609.344,weight:1,fillOpacity:.04}).addTo(state.nearbyMap);document.getElementById('nearbyMapMeta').innerHTML='<span class="zmap-pill">'+providers.length+' nearby provider(s)</span><span class="zmap-pill">Radius '+radius+' mi</span>'}
function navUrl(dest){const lat=encodeURIComponent(dest.lat),lng=encodeURIComponent(dest.lng);const isiOS=/iPad|iPhone|iPod/.test(navigator.userAgent);return isiOS?'https://maps.apple.com/?daddr='+lat+','+lng+'&dirflg=d':'https://www.google.com/maps/dir/?api=1&destination='+lat+','+lng}
async function renderJob(job){inject();if(!job?.providerId||['Completed','Cancelled'].includes(job.status)){document.getElementById('jobMapCard')?.classList.add('hidden');state.jobId=null;return}try{const t=await api('/requests/'+job.id+'/tracking');const c=t.customerLocation,p=t.providerLocation;if(!c&&!p)return;await loadLeaflet();document.getElementById('jobMapCard').classList.remove('hidden');const center=p||c;if(!state.jobMap)state.jobMap=baseMap('jobMap',[center.lat,center.lng]);if(state.customerMarker)state.customerMarker.remove();if(state.providerMarker)state.providerMarker.remove();if(state.route)state.route.remove();const pts=[];if(c){state.customerMarker=L.marker([c.lat,c.lng]).addTo(state.jobMap).bindPopup('Customer');pts.push([c.lat,c.lng])}if(p){state.providerMarker=L.marker([p.lat,p.lng]).addTo(state.jobMap).bindPopup('Provider');pts.push([p.lat,p.lng])}if(pts.length===2){state.route=L.polyline(pts,{weight:4,dashArray:'8 8'}).addTo(state.jobMap);state.jobMap.fitBounds(pts,{padding:[40,40]})}else state.jobMap.setView(pts[0],14);const d=distMiles(c,p),m=eta(d),updated=p?.updatedAt?new Date(p.updatedAt).toLocaleTimeString():null;document.getElementById('jobMapMeta').innerHTML='<span class="zmap-pill">'+t.status+'</span>'+(d==null?'':'<span class="zmap-pill">'+d.toFixed(1)+' mi</span><span class="zmap-pill">ETA ~'+m+' min</span>')+(updated?'<span class="zmap-pill">Updated '+updated+'</span>':'');const b=document.getElementById('zovroNavigate');if(me?.role==='provider'&&c){b.classList.remove('hidden');b.onclick=()=>window.open(navUrl(c),'_blank')}else b.classList.add('hidden');state.jobId=job.id}catch(e){console.warn('ZOVRO live tracking unavailable',e.message)}}
function activeAssignedJob(){return Array.isArray(jobs)?jobs.find(j=>j.providerId&&!['Completed','Cancelled'].includes(j.status)&&(me?.role==='customer'||j.providerId===me?.id)):null}
function refreshJob(){const j=activeAssignedJob();if(j)renderJob(j);else document.getElementById('jobMapCard')?.classList.add('hidden')}
window.ZOVRO_MAPS={renderNearby,renderJob,refreshJob};
window.addEventListener('DOMContentLoaded',inject);
setTimeout(inject,0);
const oldLoad=window.loadJobs;window.loadJobs=async function(){const r=await oldLoad.apply(this,arguments);refreshJob();return r};
const oldNearby=window.findNearby;window.findNearby=async function(){try{const p=await geo(),out=await api('/providers/nearby?lat='+p.lat+'&lng='+p.lng+'&service='+encodeURIComponent(document.getElementById('nearbyService').value)+'&radius=25');document.getElementById('nearbyList').innerHTML=(out.providers||[]).map(x=>'<div class="card job"><b>'+esc(x.provider.name)+'</b><p class="muted">'+esc(x.provider.service||'Local Pro')+' · '+x.distanceMiles+' mi · ETA '+x.etaMinutes+' min</p><span class="tag">⭐ '+(x.provider.stats.rating??'New')+' · '+x.provider.stats.completedJobs+' jobs</span></div>').join('')||'<div class="card job">No active nearby providers found yet.</div>';await renderNearby(p,out.providers||[],out.radiusMiles||25)}catch(e){toast(e.message)}};
setInterval(()=>{if(state.jobId&&me)refreshJob()},10000);
})();
