'use strict';
(function(){
const SUPPORT_EMAIL='support@zovro.work';
const CATEGORIES={general:'General support',account:'Account help',service:'Service request',complaint:'Complaint',payment:'Payment / refund dispute',safety:'Safety report'};
function esc2(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function ticketNo(id){return 'ZV-'+String(id||'').replace(/-/g,'').slice(0,8).toUpperCase()}
function supportDecision(text,category){return window.ZOVRO_SUPPORT_POLICY?.respond({text,category,locale:document.getElementById('supportLanguage')?.value||undefined})||{reply:'Automated support is unavailable. Contact support@zovro.work for human review.',humanReviewRequired:true,policyVersion:null,answerId:'unavailable',sources:[]}}
function aiReply(text,category){return supportDecision(text,category).reply}
function inject(){if(document.getElementById('zovroSupportCenter'))return;const profile=document.getElementById('profile');if(!profile)return;const wrap=document.createElement('div');wrap.id='zovroSupportCenter';wrap.innerHTML='<div class="sectionHead"><div><h2>Help & Support</h2><p>AI help, complaints, disputes and safety reports.</p></div></div><div class="card"><div class="bar"><button class="btn primary" onclick="ZOVRO_SUPPORT.openAI()">Automated Support</button><button class="btn ghost" onclick="ZOVRO_SUPPORT.openTicket()">⚠️ File a complaint</button><a class="btn ghost" style="text-decoration:none" href="mailto:'+SUPPORT_EMAIL+'">📩 Email support</a></div><p class="muted" style="margin-bottom:0">Phone support will be added later. For immediate police, fire or medical emergencies, call 911.</p></div><div id="zovroTicketList"></div>';profile.appendChild(wrap);const m=document.createElement('div');m.id='supportModal';m.className='modal';m.innerHTML='<div class="sheet"><h2 id="supportTitle">ZOVRO Support</h2><div id="supportAI"></div><div class="field"><label for="supportLanguage">Reply language / لغة الرد / Idioma</label><select id="supportLanguage"><option value="">Automatic / تلقائي / Automático</option><option value="en">English</option><option value="ar">العربية</option><option value="es">Español</option></select></div><div class="field"><label>Category</label><select id="supportCategory">'+Object.entries(CATEGORIES).map(([v,l])=>'<option value="'+v+'">'+l+'</option>').join('')+'</select></div><div class="field"><label>Request ID (optional)</label><input id="supportRequestId" placeholder="Link this issue to a service request"></div><div class="field"><label>Describe the issue</label><textarea id="supportText" placeholder="Tell us what happened"></textarea></div><div class="field"><label>Photo / video evidence (optional)</label><input id="supportEvidence" type="file" accept="image/*,video/*" multiple><small class="muted">Selected media stays on your device in this release; do not include highly sensitive information. Secure upload will be enabled before media evidence is accepted by support.</small></div><div class="bar"><button class="btn primary" onclick="ZOVRO_SUPPORT.askAI()">Ask support</button><button class="btn dark" onclick="ZOVRO_SUPPORT.submit()">Create ticket</button><button class="btn ghost" onclick="closeModal(\'supportModal\')">Cancel</button></div></div>';document.body.appendChild(m)}
function openAI(){if(!me)return openAuth();inject();document.getElementById('supportTitle').textContent='ZOVRO Automated Support';document.getElementById('supportAI').innerHTML='<div class="msg">Hi — I can help classify your issue and create a ticket. Human review is required for safety actions and final payment/refund decisions.</div>';document.getElementById('supportModal').classList.add('open')}
function openTicket(category='complaint'){if(!me)return openAuth();inject();document.getElementById('supportTitle').textContent='Contact ZOVRO Support';document.getElementById('supportCategory').value=category;document.getElementById('supportAI').innerHTML='';document.getElementById('supportModal').classList.add('open')}
function askAI(){const text=document.getElementById('supportText').value,cat=document.getElementById('supportCategory').value;document.getElementById('supportAI').innerHTML='<div class="msg">'+esc2(aiReply(text,cat))+'</div>'}
async function submit(){const text=document.getElementById('supportText').value.trim(),category=document.getElementById('supportCategory').value,requestId=document.getElementById('supportRequestId').value.trim();if(text.length<10)return toast('Please add more detail.');if(category==='safety'&&/immediate|danger|911|weapon|fire|medical/i.test(text))toast('If there is immediate danger, call 911.');try{const decision=supportDecision(text,category);const out=await api('/workflows',{method:'POST',body:JSON.stringify({type:'support_ticket',requestId:requestId||null,status:'received',data:{category,subject:CATEGORIES[category],description:text,priority:category==='safety'?'urgent':'normal',source:'in_app',aiTriage:decision.reply,humanReviewRequired:decision.humanReviewRequired,policyVersion:decision.policyVersion,answerId:decision.answerId,policySources:decision.sources,phoneSupport:false}})});toast('Ticket '+ticketNo(out.record.id)+' received');closeModal('supportModal');document.getElementById('supportText').value='';await loadTickets()}catch(e){toast(e.message)}}
async function loadTickets(){if(!me)return;try{const out=await api('/workflows?type=support_ticket'),box=document.getElementById('zovroTicketList');if(!box)return;const rows=out.records||[];box.innerHTML=rows.length?'<div class="sectionHead"><div><h2>Your support tickets</h2><p>Received → Under Review → Waiting for Customer → Resolved</p></div></div>'+rows.map(r=>'<div class="card job"><div class="row"><div class="grow"><b>'+ticketNo(r.id)+' · '+esc2(r.data?.subject||'Support')+'</b><p class="muted">'+esc2(r.data?.description||'')+'</p></div><span class="tag">'+esc2(r.status||'received')+'</span></div></div>').join(''):''}catch(e){console.warn('Support tickets unavailable',e.message)}}
const oldNav=window.nav;window.nav=function(id,b){const r=oldNav.apply(this,arguments);if(id==='profile')setTimeout(loadTickets,0);return r};
window.ZOVRO_SUPPORT={openAI,openTicket,askAI,submit,loadTickets};window.addEventListener('DOMContentLoaded',inject);setTimeout(inject,0);
})();
