'use strict';
// Shared by the app and future mailbox adapter. Customer text never changes policy.
(function(root,factory){if(typeof module==='object'&&module.exports)module.exports=factory();else root.ZOVRO_SUPPORT_POLICY=factory();})(typeof globalThis!=='undefined'?globalThis:this,function(){
 const version='2026-09-23.2';
 // Add exact question variants and owner-reviewed answers here. Draft entries are ignored.
 const faqs=[
  {id:'license-requirement',status:'published',source:'support.html',section:'Licensing requirements',questions:['Do I need a license to join ZOVRO?','هل الرخصة إلزامية للتسجيل؟','¿Necesito una licencia para registrarme en ZOVRO?'],en:'ZOVRO does not impose a blanket business or professional license requirement for registration. You must hold any valid licenses or permits legally required for the specific service and its location, including applicable state, local or federal requirements, before performing that service. Registration is not proof of permission to perform regulated work. A license badge requires verification.',ar:'لا يفرض ZOVRO رخصة نشاط أو مهنة على جميع المسجلين. يجب امتلاك الرخص والتصاريح السارية التي يفرضها القانون على الخدمة ومكان تنفيذها، بما يشمل متطلبات الولاية والجهات المحلية أو الفيدرالية المنطبقة، قبل تنفيذ تلك الخدمة. التسجيل لا يثبت السماح بممارسة الأعمال المنظمة قانونًا، وشارة الترخيص تحتاج إلى تحقق.'},
  {id:'marketplace',status:'published',source:'terms.html',section:'Marketplace role',questions:['¿Qué es ZOVRO?','What is ZOVRO?','ما هو زوفرو؟','ما هو ZOVRO؟'],en:'ZOVRO connects customers with independent local service providers. Providers are responsible for the services they offer.',ar:'يربط ZOVRO العملاء بمقدمي خدمات محليين مستقلين، ويتحمل مقدمو الخدمات مسؤولية الخدمات التي يقدمونها.'},
  {id:'location',status:'published',source:'privacy.html',section:'Location',questions:['¿Por qué necesitan mi ubicación?','Why do you need my location?','لماذا تحتاجون موقعي؟'],en:'Location supports nearby-provider matching, service-address assistance and live job tracking. ZOVRO requests device location when a location feature is used. You can change permission in device settings.',ar:'يُستخدم الموقع للعثور على مقدمي خدمات قريبين وتحديد عنوان الخدمة وتتبع العمل. يطلب ZOVRO الموقع عند استخدام إحدى ميزات الموقع، ويمكنك تعديل الإذن من إعدادات الجهاز.'},
  {id:'account-help',status:'published',source:'support.html',section:'Account help',questions:['¿Dónde están los ajustes de mi cuenta?','Where are my account settings?','أين إعدادات حسابي؟'],en:'Open Profile to review your account, notifications, provider details and account deletion options.',ar:'افتح الملف الشخصي لمراجعة حسابك والإشعارات وبيانات مقدم الخدمة وخيارات حذف الحساب.'},
  {id:'active-request',status:'published',source:'support.html',section:'Service request help',questions:['¿Cómo contacto a mi proveedor asignado?','How do I contact my assigned provider?','كيف أتواصل مع مقدم الخدمة المعين؟'],en:'Open Requests or Messages to review an active job, contact the assigned provider and follow job status.',ar:'افتح الطلبات أو الرسائل لمراجعة العمل الجاري والتواصل مع مقدم الخدمة المعين ومتابعة حالة الطلب.'},
  {id:'provider-license',status:'published',source:'support.html',section:'Provider verification',questions:['¿La verificación reemplaza una licencia?','Does verification replace a license?','هل التحقق يغني عن الترخيص؟'],en:'Verification status does not replace any legal license, permit or insurance requirement. Providers should keep qualification information accurate.',ar:'حالة التحقق لا تغني عن أي ترخيص أو تصريح أو تأمين مطلوب قانونًا. يجب على مقدم الخدمة إبقاء معلومات مؤهلاته دقيقة.'}
 ];
 const spanish={
 'license-requirement':'ZOVRO no exige una licencia comercial o profesional a todos los usuarios para registrarse. Antes de realizar un servicio, debes tener las licencias o permisos vigentes exigidos legalmente para ese servicio y su ubicación, incluidos los requisitos estatales, locales o federales aplicables. Registrarse no demuestra autorización para realizar trabajos regulados. La insignia de licencia requiere verificación.',
 'marketplace':'ZOVRO conecta a clientes con proveedores locales independientes. Los proveedores son responsables de los servicios que ofrecen.',
 'location':'La ubicación permite encontrar proveedores cercanos, ayudar con la dirección del servicio y seguir el trabajo. ZOVRO solicita la ubicación al utilizar una función de ubicación. Puedes cambiar el permiso en los ajustes del dispositivo.',
 'account-help':'Abre Perfil para revisar tu cuenta, notificaciones, información del proveedor y opciones para eliminar la cuenta.',
 'active-request':'Abre Solicitudes o Mensajes para revisar un trabajo activo, contactar al proveedor asignado y seguir su estado.',
 'provider-license':'La verificación no sustituye ninguna licencia, permiso o seguro exigido por la ley. Los proveedores deben mantener actualizada la información sobre sus cualificaciones.',
 'safety':'Si existe peligro inmediato o necesitas policía, bomberos o asistencia médica, llama al 911. El SOS de ZOVRO no sustituye los servicios de emergencia. Este asunto requiere revisión humana.',
 'payment-review':'Las preguntas sobre pagos, cargos y reembolsos requieren revisión del equipo de soporte. Esta respuesta automática no puede aprobar reembolsos, modificar cargos ni prometer importes o plazos.',
 'human-review':'Las políticas y preguntas frecuentes disponibles no ofrecen una respuesta confirmada a esta pregunta. Envíala a support@zovro.work o crea un ticket para revisión humana. No envíes contraseñas, códigos de verificación ni datos completos de tarjetas.'
 };
 function normalize(value){return String(value||'').normalize('NFKC').toLowerCase().replace(/[\u064B-\u065F\u0670]/g,'').replace(/[أإآ]/g,'ا').replace(/[¿?¡؟!.،,]/g,'').replace(/\s+/g,' ').trim();}
 function respond({text='',category='general',locale}={}){
  text=String(text).slice(0,10000);const requested=String(locale||'').toLowerCase().split('-')[0];const lang=['ar','en','es'].includes(requested)?requested:/[\u0600-\u06ff]/.test(text)?'ar':/[¿¡ñáéíóúü]|\b(hola|necesito|ayuda|quiero|reembolso|pago|cuenta|gracias|peligro|cobro|cobraron|tarjeta|emergencia)\b/i.test(text)?'es':'en';
  const wrap=(id,en,ar,source,section,humanReviewRequired)=>({policyVersion:version,answerId:id,language:lang,reply:lang==='ar'?ar:lang==='es'?spanish[id]:en,sources:source?[{path:source,section}]:[],humanReviewRequired,automated:true});
  if(category==='safety'||/\b(danger|threat|assault|emergency|911|weapon|fire|peligro|amenaza|emergencia|incendio|asalto)\b|خطر|تهديد|اعتداء|طوارئ|حريق/.test(text.toLowerCase()))return wrap('safety','If anyone is in immediate danger or needs police, fire or medical assistance, call 911. ZOVRO SOS does not replace emergency services. This issue needs human review.','إذا كان هناك خطر فوري أو حاجة للشرطة أو الإطفاء أو الإسعاف فاتصل بـ911. خدمة SOS في ZOVRO لا تحل محل خدمات الطوارئ. هذه المسألة تحتاج مراجعة بشرية.','terms.html','Safety',true);
  if(category==='payment'||/\b(refund|payment|charge|charged|money|fee|fees|payout|card|reembolso|pago|pagos|cobro|cobraron|tarjeta|dinero|tarifa|tarifas)\b|استرداد|استرجاع|دفع|رسوم|خصم|بطاق/.test(text.toLowerCase()))return wrap('payment-review','Payment, fee and refund questions require support review. This automated reply cannot approve a refund, change a charge or promise an amount or processing time.','تحتاج أسئلة الدفع والرسوم والاسترداد إلى مراجعة الدعم. لا يستطيع هذا الرد الآلي الموافقة على استرداد أو تعديل مبلغ أو الوعد بقيمة أو مدة تنفيذ.',null,null,true);
  if(category!=='general')return fallback();
  const match=faqs.find(f=>f.status==='published'&&f.questions.some(q=>normalize(q)===normalize(text)));
  if(match)return wrap(match.id,match.en,match.ar,match.source,match.section,false);
  return fallback();
  function fallback(){return wrap('human-review','The available company policies and FAQ do not provide a confirmed answer to this question. Please send it to support@zovro.work or create a support ticket for human review. Do not send passwords, verification codes or full card details.','لا تتضمن سياسات الشركة والأسئلة الشائعة المتاحة جوابًا مؤكدًا لهذا السؤال. أرسله إلى support@zovro.work أو أنشئ تذكرة دعم للمراجعة البشرية. لا ترسل كلمات المرور أو رموز التحقق أو بيانات البطاقة الكاملة.',null,null,true);}
 }
 return {version,respond};
});
