'use strict';
(function(){
const SUPPORT_EMAIL='support@zovro.net';
const CATEGORIES={general:'General support',account:'Account help',service:'Service request',complaint:'Complaint',payment:'Payment / refund dispute',safety:'Safety report'};
function esc2(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function ticketNo(id){return 'ZV-'+String(id||'').replace(/-/g,'').slice(0,8).toUpperCase()}
function aiReply(text,category){const q=String(text||'').toLowerCase();if(category==='safety'||/danger|threat|unsafe|assault|911|emergency/.test(q))return 'I can record this as a safety report for ZOVRO review. If anyone is in immediate danger or needs police, fire, or medical help, call 911 now. ZOVRO SOS is not a replacement for emergency services.';if(category==='payment'||/refund|charge|payment|card|money/.test(q))return 'I can open a payment or refund dispute and preserve the details for review. I will not make a final refund decision automatically.';if(category==='complaint'||/complain|complaint|bad service|problem/.test(q))return 'I can create a complaint ticket, link it to your request when you provide the request ID, and keep its status in your account.';if(/password|login|account/.test(q))return 'For account access, use Profile & Security. If the issue continues, create an Account help ticket and support can review it.';if(/provider|job|request|service/.test(q))return 'For an active service, open Requests to contact the assigned provider. I can also create a support ticket linked to that request.';return 'I can help classify the issue and create a support ticket. Choose the closest category and describe what happened; sensitive safety and payment decisions are sent for human review.'}
function inject(){if(document.getElementById('zovroSupportCenter'))return;const profile=document.getElementById('profile');if(!profile)return;const wrap=document.createElement('div');wrap.id='zovroSupportCenter';wrap.innerHTML='<div class="sectionHead"><div><h2>Help & Support</h2><p>AI help, complaints, disputes and safety reports.</p></div></div><div class="card"><div class="bar"><button class="btn primary" onclick="ZOVRO_SUPPORT.openAI()">🤖 AI Support</button><button class="btn ghost" onclick="ZOVRO_SUPPORT.openTicket()">⚠️ File a complaint</button><a class="btn ghost" style="text-decoration:none" href="mailto:'+SUPPORT_EMAIL+'">📩 Email support</a></div><p class="muted" style="margin-bottom:0">Phone support will be added later. For immediate police, fire or medical emergencies, call 911.</p></div><div id="zovroTicketList"></div>';profile.appendChild(wrap);const m=document.createElement('div');m.id='supportModal';m.className='modal';m.innerHTML='<div class="sheet"><h2 id="supportTitle">ZOVRO Support</h2><div id="supportAI"></div><div class="field"><label>Category</label><select id="supportCategory">'+Object.entries(CATEGORIES).map(([v,l])=>'<option value="'+v+'">'+l+'</option>').join('')+'</select></div><div class="field"><label>Request ID (optional)</label><input id="supportRequestId" placeholder="Link this issue to a service request"></div><div class="field"><label>Describe the issue</label><textarea id="supportText" placeholder="Tell us what happened"></textarea></div><div class="field"><label>Photo / video evidence (optional)</label><input id="supportEvidence" type="file" accept="image/*,video/*" multiple><small class="muted">Selected media stays on your device in this release; do not include highly sensitive information. Secure upload will be enabled before media evidence is accepted by support.</small></div><div class="bar"><button class="btn primary" onclick="ZOVRO_SUPPORT.askAI()">Ask AI</button><button class="btn dark" onclick="ZOVRO_SUPPORT.submit()">Create ticket</button><button class="btn ghost" onclick="closeModal(\'supportModal\')">Cancel</button></div></div>';document.body.appendChild(m)}
function openAI(){if(!me)return openAuth();inject();document.getElementById('supportTitle').textContent='ZOVRO AI Support';document.getElementById('supportAI').innerHTML='<div class="msg">Hi — I can help classify your issue and create a ticket. Human review is required for safety actions and final payment/refund decisions.</div>';document.getElementById('supportModal').classList.add('open')}
function openTicket(category='complaint'){if(!me)return openAuth();inject();document.getElementById('supportTitle').textContent='Contact ZOVRO Support';document.getElementById('supportCategory').value=category;document.getElementById('supportAI').innerHTML='';document.getElementById('supportModal').classList.add('open')}
function askAI(){const text=document.getElementById('supportText').value,cat=document.getElementById('supportCategory').value;document.getElementById('supportAI').innerHTML='<div class="msg">'+esc2(aiReply(text,cat))+'</div>'}
async function submit(){const text=document.getElementById('supportText').value.trim(),category=document.getElementById('supportCategory').value,requestId=document.getElementById('supportRequestId').value.trim();if(text.length<10)return toast('Please add more detail.');if(category==='safety'&&/immediate|danger|911|weapon|fire|medical/i.test(text))toast('If there is immediate danger, call 911.');try{const out=await api('/workflows',{method:'POST',body:JSON.stringify({type:'support_ticket',requestId:requestId||null,status:'received',data:{category,subject:CATEGORIES[category],description:text,priority:category==='safety'?'urgent':'normal',source:'in_app',aiTriage:aiReply(text,category),humanReviewRequired:['safety','payment'].includes(category),phoneSupport:false}})});toast('Ticket '+ticketNo(out.record.id)+' received');closeModal('supportModal');document.getElementById('supportText').value='';await loadTickets()}catch(e){toast(e.message)}}
async function loadTickets(){if(!me)return;try{const out=await api('/workflows?type=support_ticket'),box=document.getElementById('zovroTicketList');if(!box)return;const rows=out.records||[];box.innerHTML=rows.length?'<div class="sectionHead"><div><h2>Your support tickets</h2><p>Received → Under Review → Waiting for Customer → Resolved</p></div></div>'+rows.map(r=>'<div class="card job"><div class="row"><div class="grow"><b>'+ticketNo(r.id)+' · '+esc2(r.data?.subject||'Support')+'</b><p class="muted">'+esc2(r.data?.description||'')+'</p></div><span class="tag">'+esc2(r.status||'received')+'</span></div></div>').join(''):''}catch(e){console.warn('Support tickets unavailable',e.message)}}
const oldNav=window.nav;window.nav=function(id,b){const r=oldNav.apply(this,arguments);if(id==='profile')setTimeout(loadTickets,0);return r};
window.ZOVRO_SUPPORT={openAI,openTicket,askAI,submit,loadTickets};window.addEventListener('DOMContentLoaded',inject);setTimeout(inject,0);
})();
