'use strict';
const {test}=require('node:test'),assert=require('node:assert/strict');
const {createAdminRequests}=require('./admin-requests');
function harness(role='admin',session={uid:'a',role:'admin'}){const db={users:[{id:'a',role},{id:'c',name:'Customer',phone:'private'}],requests:[{id:'req1',customerId:'c',service:'Roadside Assistance',status:'Looking for providers',createdAt:'2026-09-25T00:00:00Z',location:{lat:42.3,lng:-83.2,accuracy:12,capturedAt:'2026-09-24T23:59:55Z'},address:'Private address',details:'Need help',securityCode:'4321'},{id:'req2',customerId:'c',service:'Plumbing',createdAt:'2026-09-24T00:00:00Z',location:null}]};let result,writes=0,audits=[];const fn=createAdminRequests({auth:()=>session,readDb:()=>db,json:(_,code,data)=>result={code,data},limited:()=>false,audit:(_,actor,action,meta)=>audits.push({actor,action,meta}),writeDb:()=>writes++});return {db,audits,get writes(){return writes},async get(path='',method='GET'){await fn({method},{},new URL('https://example.test/api/admin/requests'+path));return result}}}
test('no auth, forged token role, providers and inactive admins cannot read',async()=>{assert.equal((await harness('admin',null).get()).code,401);for(const role of ['customer','provider'])assert.equal((await harness(role).get('/req1')).code,403);const h=harness();h.db.users[0].accountStatus='disabled';assert.equal((await h.get('/req1')).code,403)});
test('list shows receipt and coordinate presence without exact location or identity',async()=>{const h=harness(),r=await h.get();assert.equal(r.code,200);assert.equal(r.data.requests[0].hasCoordinates,true);assert.equal(r.data.requests[1].hasCoordinates,false);const out=JSON.stringify(r.data);for(const secret of ['42.3','-83.2','Private address','4321','Customer','phone'])assert(!out.includes(secret));assert.equal(h.writes,0)});
test('detail returns saved coordinates and records only request ID in audit',async()=>{const h=harness(),r=await h.get('/req1');assert.equal(r.data.request.location.accuracy,12);assert.equal(r.data.request.location.lat,42.3);assert.equal(r.data.request.customer.name,'Customer');assert(!JSON.stringify(r.data).includes('4321'));assert(!JSON.stringify(r.data).includes('phone'));assert.equal(h.writes,1);assert.deepEqual(h.audits[0].meta,{requestId:'req1'})});
test('no GPS and legacy metadata are shown as absent without invented values',async()=>{const h=harness();assert.equal((await h.get('/req2')).data.request.location,null);delete h.db.requests[0].location.accuracy;delete h.db.requests[0].location.capturedAt;const r=await h.get('/req1');assert.equal(r.data.request.location.accuracy,null);assert.equal(r.data.request.location.capturedAt,null)});
test('exact ID filter, pagination, missing ID and read-only endpoint',async()=>{const h=harness();assert.equal((await h.get('?id=req2')).data.requests.length,1);assert.equal((await h.get('/missing')).code,404);assert.equal((await h.get('/req1','POST')).code,405);for(let i=0;i<60;i++)h.db.requests.push({id:'extra'+i,createdAt:'2026-09-20'});let r=await h.get();assert.equal(r.data.requests.length,50);assert.equal(r.data.nextOffset,50);r=await h.get('?offset=50');assert.equal(r.data.requests.length,12);assert.equal(r.data.nextOffset,null)});
test('service worker never intercepts or caches API and private reads',()=>{const listeners={},fs=require('node:fs'),vm=require('node:vm');vm.runInNewContext(fs.readFileSync(require('node:path').join(__dirname,'../service-worker.js'),'utf8'),{URL,self:{location:{origin:'https://zovro.work'},addEventListener:(name,fn)=>listeners[name]=fn}});for(const [path,cache] of [['/api/admin/requests/req1','default'],['/api/me','default'],['/admin.html','no-store']]){let intercepted=false;listeners.fetch({request:{method:'GET',url:'https://zovro.work'+path,cache},respondWith:()=>intercepted=true});assert.equal(intercepted,false)}});
