'use strict';
const {test}=require('node:test');const assert=require('node:assert/strict');
const {createRecovery,verifyProvider}=require('./password-recovery');
function fixture(){
  let db={users:[{id:'u',phone:'+13135551234',phoneVerified:true,passwordHash:'original',accountStatus:'active'}],workflows:[],deviceSessions:[{id:'a',userId:'u'},{id:'b',userId:'u'},{id:'c',userId:'other'}],audit:[]};
  let time=10000000,startCalls=0,checkCalls=0,approved=true,available=true,onCheck=null;
  const dependencies={readDb:()=>structuredClone(db),writeDb:value=>{db=structuredClone(value)},body:async req=>req.payload,json:(res,status,data)=>Object.assign(res,{status,data}),limited:()=>false,hash:p=>'hashed:'+p,validPassword:p=>typeof p==='string'&&p.length>=10&&p.length<=128&&/[a-z]/i.test(p)&&/\d/.test(p),audit:(db,u,action)=>db.audit.push({action,user:u.uid}),now:()=>time,provider:{configured:()=>available,start:async()=>{startCalls++;return 'VE'+'a'.repeat(32)},check:async()=>{checkCalls++;if(onCheck)await onCheck();return approved}}};
  let handler=createRecovery(dependencies);
  return {get db(){return db},get starts(){return startCalls},get checks(){return checkCalls},set approved(v){approved=v},set available(v){available=v},set onCheck(v){onCheck=v},advance(ms){time+=ms},restart(){handler=createRecovery(dependencies)},async call(path,payload,method='POST'){const res={};await handler({method,payload},res,{pathname:'/api/auth/'+path});return res;}};
}
const phone={phone:'+13135551234'};
const reset=challenge=>({challenge,code:'123456',newPassword:'newPassword123'});
test('disabled configuration fails closed and sends nothing',async()=>{const f=fixture();f.available=false;assert.equal((await f.call('forgot-password',phone)).status,503);assert.equal(f.starts,0)});
test('success revokes all account sessions and challenge cannot replay',async()=>{const f=fixture(),r=await f.call('forgot-password',phone);assert.equal(r.status,202);assert.equal(f.db.workflows[0].challengeHash.length,64);assert.notEqual(f.db.workflows[0].challengeHash,r.data.challenge);assert.equal((await f.call('reset-password',reset(r.data.challenge))).status,200);assert.equal(f.db.users[0].passwordHash,'hashed:newPassword123');assert.deepEqual(f.db.deviceSessions,[{id:'c',userId:'other'}]);assert.equal((await f.call('reset-password',reset(r.data.challenge))).status,400);assert.equal(f.checks,1)});
test('unknown and unverified accounts get generic response without SMS',async()=>{for(const change of [f=>f.db.users.splice(0),f=>{f.db.users[0].phoneVerified=false}]){const f=fixture();change(f);const r=await f.call('forgot-password',phone);assert.equal(r.status,202);assert.equal(r.data.challenge.length,64);assert.equal(f.starts,0);assert.equal((await f.call('reset-password',reset(r.data.challenge))).status,400)}});
test('expiry survives restart',async()=>{const f=fixture(),r=await f.call('forgot-password',phone);f.restart();f.advance(600001);assert.equal((await f.call('reset-password',reset(r.data.challenge))).status,400);assert.equal(f.checks,0)});
test('five failed attempts lock recovery across restart',async()=>{const f=fixture(),r=await f.call('forgot-password',phone);f.approved=false;for(let i=0;i<6;i++){f.restart();assert.equal((await f.call('reset-password',reset(r.data.challenge))).status,400)}assert.equal(f.checks,5);assert.equal(f.db.users[0].passwordHash,'original')});
test('send throttling survives restart and does not expose account',async()=>{const f=fixture();await f.call('forgot-password',phone);f.restart();assert.equal((await f.call('forgot-password',phone)).status,202);assert.equal(f.starts,1)});
test('concurrent checks cannot both consume challenge',async()=>{const f=fixture(),r=await f.call('forgot-password',phone);let release;const barrier=new Promise(resolve=>{release=resolve});f.onCheck=()=>barrier;const first=f.call('reset-password',reset(r.data.challenge));await new Promise(resolve=>setImmediate(resolve));assert.equal((await f.call('reset-password',reset(r.data.challenge))).status,400);release();assert.equal((await first).status,200);assert.equal(f.checks,1)});
test('account password change during provider check invalidates reset',async()=>{const f=fixture(),r=await f.call('forgot-password',phone);f.onCheck=()=>{f.db.users[0].passwordHash='changed-elsewhere'};assert.equal((await f.call('reset-password',reset(r.data.challenge))).status,400);assert.equal(f.db.users[0].passwordHash,'changed-elsewhere')});
test('provider transport errors never change password',async()=>{const f=fixture(),r=await f.call('forgot-password',phone);f.onCheck=()=>{throw Error('outage')};assert.equal((await f.call('reset-password',reset(r.data.challenge))).status,400);assert.equal(f.db.users[0].passwordHash,'original')});
test('unrelated account mutations are preserved across await',async()=>{const f=fixture(),r=await f.call('forgot-password',phone);f.onCheck=()=>f.db.users.push({id:'other'});await f.call('reset-password',reset(r.data.challenge));assert.equal(f.db.users.length,2)});
test('provider requires explicit activation and binds approval to SID',async()=>{let calls=0;const env={TWILIO_ACCOUNT_SID:'AC'+'a'.repeat(32),TWILIO_AUTH_TOKEN:'fake',TWILIO_RECOVERY_VERIFY_SERVICE_SID:'VA'+'b'.repeat(32)};const p=verifyProvider(env,async(url,options)=>{calls++;assert.ok(options.body.includes('VerificationSid='));return {ok:true,json:async()=>({status:'approved',sid:'VE'+'c'.repeat(32)})}});assert.equal(p.configured(),false);env.ZOVRO_PASSWORD_RECOVERY_ENABLED='true';assert.equal(p.configured(),true);assert.equal(await p.check('VE'+'a'.repeat(32),'123456'),false);assert.equal(calls,1)});
test('verified legacy US phone without plus can recover without changing identity',async()=>{const f=fixture();f.db.users[0].phone='13135551234';const r=await f.call('forgot-password',phone);assert.equal(f.starts,1);assert.equal((await f.call('reset-password',reset(r.data.challenge))).status,200);assert.equal(f.db.users[0].phone,'13135551234')});
test('ambiguous canonical phones never receive a recovery code',async()=>{const f=fixture();f.db.users.push({...f.db.users[0],id:'other',phone:'13135551234'});const r=await f.call('forgot-password',phone);assert.equal(r.status,202);assert.equal(f.starts,0);assert.equal((await f.call('reset-password',reset(r.data.challenge))).status,400)});

test('email fallback queues a sealed OTP and completes recovery without Twilio',async()=>{
  let db={users:[{id:'u',phone:'+13135551234',email:'user@example.com',phoneVerified:false,passwordHash:'original',accountStatus:'active'}],workflows:[],deviceSessions:[{id:'a',userId:'u'}],audit:[]};
  let time=20000000;const workerToken='w'.repeat(64);
  const deps={readDb:()=>structuredClone(db),writeDb:v=>{db=structuredClone(v)},body:async req=>req.payload||{},json:(res,status,data)=>Object.assign(res,{status,data}),limited:()=>false,hash:p=>'hashed:'+p,validPassword:p=>typeof p==='string'&&p.length>=10&&/[A-Za-z]/.test(p)&&/\d/.test(p),audit:(d,u,action)=>d.audit.push({action,user:u.uid}),now:()=>time,workerToken,provider:{configured:()=>false,start:async()=>{throw Error('disabled')},check:async()=>false}};
  const handler=createRecovery(deps);
  const call=async(path,payload={},method='POST',headers={})=>{const res={};await handler({method,payload,headers},res,{pathname:path});return res};
  const status=await call('/api/auth/recovery/status',{},'GET');assert.equal(status.status,200);assert.equal(status.data.available,true);
  const start=await call('/api/auth/forgot-password',{phone:'+13135551234'});assert.equal(start.status,202);
  assert.equal(db.workflows[0].channel,'email');assert.equal(db.workflows[0].status,'email_pending');assert.ok(db.workflows[0].deliveryEmail);assert.ok(db.workflows[0].deliveryCode);assert.equal(String(db.workflows[0].deliveryEmail).includes('user@example.com'),false);
  const tasks=await call('/api/internal/recovery-email/tasks',{},'GET',{'x-zovro-recovery-worker-token':workerToken});assert.equal(tasks.status,200);assert.equal(tasks.data.tasks.length,1);
  assert.equal(tasks.data.tasks[0].email,'user@example.com');assert.match(tasks.data.tasks[0].code,/^\d{6}$/);
  const ack=await call('/api/internal/recovery-email/result',{id:tasks.data.tasks[0].id,delivered:true},'POST',{'x-zovro-recovery-worker-token':workerToken});assert.equal(ack.status,200);
  const resetResult=await call('/api/auth/reset-password',{challenge:start.data.challenge,code:tasks.data.tasks[0].code,newPassword:'newPassword123'});
  assert.equal(resetResult.status,200);assert.equal(db.users[0].passwordHash,'hashed:newPassword123');assert.equal(db.deviceSessions.length,0);
});
test('email recovery worker endpoint hides behind a 404 without its token',async()=>{
  let db={users:[],workflows:[],deviceSessions:[],audit:[]};const handler=createRecovery({readDb:()=>structuredClone(db),writeDb:v=>{db=structuredClone(v)},body:async req=>req.payload||{},json:(res,status,data)=>Object.assign(res,{status,data}),limited:()=>false,hash:x=>x,validPassword:()=>true,audit:()=>{},workerToken:'w'.repeat(64),provider:{configured:()=>false,start:async()=>null,check:async()=>false}});
  const res={};await handler({method:'GET',headers:{}},res,{pathname:'/api/internal/recovery-email/tasks'});assert.equal(res.status,404);
});
