'use strict';
const crypto=require('crypto');
const STRIPE_API='https://api.stripe.com/v1';
const SECRET_KEY=String(process.env.STRIPE_SECRET_KEY||'').trim();
const WEBHOOK_SECRET=String(process.env.STRIPE_WEBHOOK_SECRET||'').trim();
const STRIPE_API_VERSION=String(process.env.STRIPE_API_VERSION||'').trim();
const FEE_BPS=Number(process.env.ZOVRO_PLATFORM_FEE_BPS||0);
const CURRENCY=String(process.env.ZOVRO_PAYMENT_CURRENCY||'usd').toLowerCase();
function configured(){return /^sk_(test|live)_/.test(SECRET_KEY)}
function webhookConfigured(){return /^whsec_/.test(WEBHOOK_SECRET)}
function feeBps(){return Number.isInteger(FEE_BPS)&&FEE_BPS>=0&&FEE_BPS<=5000?FEE_BPS:0}
function moneySplit(amountCents){const amount=Math.round(Number(amountCents));if(!Number.isInteger(amount)||amount<100||amount>5000000)throw new Error('Payment amount must be between $1.00 and $50,000.00');const platformFee=Math.floor(amount*feeBps()/10000);return {amountCents:amount,platformFeeCents:platformFee,providerAmountCents:amount-platformFee}}
function encode(params,prefix,out){out=out||new URLSearchParams();for(const [k,v] of Object.entries(params||{})){if(v===undefined||v===null)continue;const key=prefix?`${prefix}[${k}]`:k;if(typeof v==='object'&&!Array.isArray(v))encode(v,key,out);else if(Array.isArray(v))v.forEach((x,i)=>out.append(`${key}[${i}]`,String(x)));else out.append(key,String(v))}return out}
async function stripeRequest(method,path,params={},idempotencyKey,extraHeaders={}){if(!configured())throw new Error('Stripe is not configured');const headers={authorization:`Bearer ${SECRET_KEY}`,...extraHeaders};let url=STRIPE_API+path,body;if(method==='GET'){const q=encode(params).toString();if(q)url+='?'+q}else{headers['content-type']='application/x-www-form-urlencoded';if(idempotencyKey)headers['idempotency-key']=idempotencyKey;body=encode(params).toString()}const res=await fetch(url,{method,headers,body});const data=await res.json().catch(()=>({}));if(!res.ok){const e=new Error(data?.error?.message||`Stripe request failed (${res.status})`);e.code=data?.error?.code||'stripe_error';e.status=res.status;throw e}return data}
async function createCustomer({userId,name,email,phone}){const p=await stripeRequest('POST','/customers',{name:name||undefined,email:email||undefined,phone:phone||undefined,metadata:{zovro_user_id:userId}},`zovro-customer-${userId}`);if(!p?.id||!/^cus_/.test(p.id))throw new Error('Stripe customer creation failed');return p}
async function createEphemeralKey(customerId){if(!/^cus_/.test(String(customerId||'')))throw new Error('Stripe customer is invalid');const headers={};if(STRIPE_API_VERSION)headers['stripe-version']=STRIPE_API_VERSION;const p=await stripeRequest('POST','/ephemeral_keys',{customer:customerId},undefined,headers);if(!p?.secret)throw new Error('Stripe ephemeral key creation failed');return p}
async function createPaymentIntent({requestId,customerId,providerId,amountCents,stripeCustomerId}){const split=moneySplit(amountCents);const p=await stripeRequest('POST','/payment_intents',{amount:split.amountCents,currency:CURRENCY,customer:stripeCustomerId||undefined,setup_future_usage:stripeCustomerId?'on_session':undefined,'automatic_payment_methods[enabled]':'true',transfer_group:`ZOVRO_${requestId}`,description:`ZOVRO service request ${requestId}`,metadata:{zovro_request_id:requestId,zovro_customer_id:customerId,zovro_provider_id:providerId||'',zovro_platform_fee_cents:split.platformFeeCents,zovro_provider_amount_cents:split.providerAmountCents}},`zovro-pi-${requestId}-${split.amountCents}`);return {intent:p,split}}
async function createTransfer({requestId,providerAccountId,amountCents,chargeId}){if(!providerAccountId||!/^acct_/.test(providerAccountId))throw new Error('Provider payout account is not ready');return stripeRequest('POST','/transfers',{amount:Math.round(amountCents),currency:CURRENCY,destination:providerAccountId,source_transaction:chargeId||undefined,transfer_group:`ZOVRO_${requestId}`,metadata:{zovro_request_id:requestId}},`zovro-transfer-${requestId}`)}
async function createRefund({requestId,paymentIntentId,amountCents}){const params={payment_intent:paymentIntentId,metadata:{zovro_request_id:requestId}};if(amountCents)params.amount=Math.round(amountCents);return stripeRequest('POST','/refunds',params,`zovro-refund-${requestId}-${amountCents||'full'}`)}
function verifyWebhook(raw,signatureHeader,toleranceSeconds=300){if(!webhookConfigured())throw new Error('Stripe webhook is not configured');const parts=String(signatureHeader||'').split(',').map(x=>x.trim());const t=parts.find(x=>x.startsWith('t='))?.slice(2);const signatures=parts.filter(x=>x.startsWith('v1=')).map(x=>x.slice(3));if(!t||!signatures.length)throw new Error('Invalid Stripe signature');if(Math.abs(Date.now()/1000-Number(t))>toleranceSeconds)throw new Error('Stripe signature timestamp outside tolerance');const expected=crypto.createHmac('sha256',WEBHOOK_SECRET).update(`${t}.${raw}`).digest('hex');const a=Buffer.from(expected,'hex');const ok=signatures.some(s=>{try{const b=Buffer.from(s,'hex');return a.length===b.length&&crypto.timingSafeEqual(a,b)}catch{return false}});if(!ok)throw new Error('Invalid Stripe signature');return JSON.parse(raw)}
module.exports={configured,webhookConfigured,feeBps,currency:CURRENCY,moneySplit,createCustomer,createEphemeralKey,createPaymentIntent,createTransfer,createRefund,verifyWebhook};
