'use strict';
const {test}=require('node:test'),assert=require('node:assert/strict');
const {createPhoneVerification}=require('./phone-verification');
function fixture(){let db={users:[{id:'u',phone:'13135550123',passwordHash:'hash',phoneVerified:false}],workflows:[],audit:[]},time=10000000,actor={uid:'u',sid:'session'},available=true,approved=true,starts=0,checks=0,onCheck=null,onStart=null;
const deps={readDb:()=>structuredClone(db),writeDb:x=>{db=structuredClone(x)},body:async req=>req.payload,json:(res,status,data)=>Object.assign(res,{status,data}),limited:()=>false,auth:()=>actor,audit:(d,a,event)=>d.audit.push({event}),now:()=>time,provider:{configured:()=>available,start:async phone=>{starts++;assert.equal(phone,'+13135550123');if(onStart)await onStart();return 'VE'+'a'.repeat(32)},check:async()=>{checks++;if(onCheck)await onCheck();return approved}}};let handler=createPhoneVerification(deps);
return {get db(){return db},get starts(){return starts},get checks(){return checks},set actor(x){actor=x},set available(x){available=x},set approved(x){approved=x},set onCheck(x){onCheck=x},set onStart(x){onStart=x},advance(x){time+=x},restart(){handler=createPhoneVerification(deps)},async call(path,payload={},method='POST'){const res={};await handler({method,payload},res,{pathname:'/api/auth/phone/'+path});return res;}}}
const confirm=challenge=>({challenge,code:'123456'});
test('requires authentication and configured provider',async()=>{const f=fixture();f.actor=null;assert.equal((await f.call('start')).status,401);f.actor={uid:'u',sid:'session'};f.available=false;assert.equal((await f.call('start')).status,503);assert.equal(f.starts,0)});
test('verification binds registered number, confirms only after OTP, cannot replay',async()=>{const f=fixture(),r=await f.call('start',{phone:'+19999999999',userId:'other'});assert.equal(r.status,202);assert.equal(f.db.users[0].phoneVerified,false);assert.equal((await f.call('confirm',confirm(r.data.challenge))).status,200);assert.equal(f.db.users[0].phoneVerified,true);assert.equal(f.db.users[0].phone,'13135550123');assert.equal((await f.call('confirm',confirm(r.data.challenge))).status,400);assert.equal(f.checks,1)});
test('request rate limit persists across restart',async()=>{const f=fixture();await f.call('start');f.restart();assert.equal((await f.call('start')).status,429);assert.equal(f.starts,1)});
test('five bad codes lock the challenge',async()=>{const f=fixture(),r=await f.call('start');f.approved=false;for(let i=0;i<6;i++){f.restart();assert.equal((await f.call('confirm',confirm(r.data.challenge))).status,400)}assert.equal(f.checks,5);assert.equal(f.db.users[0].phoneVerified,false)});
test('expiry, different session, and account deactivation reject',async()=>{for(const change of [f=>f.advance(600001),f=>{f.actor={uid:'u',sid:'other'}},f=>{f.db.users[0].accountStatus='deleted'}]){const f=fixture(),r=await f.call('start');change(f);assert.notEqual((await f.call('confirm',confirm(r.data.challenge))).status,200);assert.equal(f.db.users[0].phoneVerified,false)}});
test('password or phone change while verifying prevents confirmation',async()=>{for(const field of ['passwordHash','phone']){const f=fixture(),r=await f.call('start');f.onCheck=()=>{f.db.users[0][field]='changed'};assert.equal((await f.call('confirm',confirm(r.data.challenge))).status,400);assert.equal(f.db.users[0].phoneVerified,false)}});
test('provider failure never verifies phone',async()=>{const f=fixture();f.onStart=()=>{throw Error('outage')};assert.equal((await f.call('start')).status,503);assert.equal(f.db.users[0].phoneVerified,false)});
test('revoked session during send prevents usable challenge',async()=>{const f=fixture();f.onStart=()=>{f.actor=null};assert.equal((await f.call('start')).status,401);assert.equal(f.db.users[0].phoneVerified,false)});
test('concurrent confirmation consumes once',async()=>{const f=fixture(),r=await f.call('start');let release;f.onCheck=()=>new Promise(resolve=>{release=resolve});const first=f.call('confirm',confirm(r.data.challenge));await new Promise(resolve=>setImmediate(resolve));assert.equal((await f.call('confirm',confirm(r.data.challenge))).status,400);release();assert.equal((await first).status,200);assert.equal(f.checks,1)});
test('ambiguous canonical phone refuses verification',async()=>{const f=fixture();f.db.users.push({id:'other',phone:'+13135550123'});assert.equal((await f.call('start')).status,409);assert.equal(f.starts,0)});
