'use strict';
const http=require('http'), fs=require('fs'), path=require('path'), crypto=require('crypto');
const {readDb,writeDb,closeDb,dbInfo}=require('./database');
const PORT=Number(process.env.PORT||8787), ROOT=path.resolve(__dirname,'..'), DATA=path.join(__dirname,'data');
const IS_PROD=process.env.NODE_ENV==='production';
const APP_VERSION=process.env.ZOVRO_APP_VERSION||'1.0.0', STAGE='FINAL', STARTED_AT=Date.now();
const ALLOWED_ORIGINS=new Set(String(process.env.ZOVRO_ALLOWED_ORIGINS||'http://localhost,https://localhost,capacitor://localhost').split(',').map(x=>x.trim()).filter(Boolean));
const SECRET=process.env.ZOVRO_SECRET||'dev-only-change-before-production';
const OPS_TOKEN=String(process.env.ZOVRO_OPS_TOKEN||'');
const metrics={requests:0,responses2xx:0,responses4xx:0,responses5xx:0,errors:0,totalResponseMs:0,lastErrorAt:null};
function logEvent(level,event,meta={}){const row={time:new Date().toISOString(),level,event,stage:STAGE,version:APP_VERSION,...meta};const out=JSON.stringify(row);if(level==='error')console.error(out);else console.log(out)}
function metricsSnapshot(){const handled=metrics.responses2xx+metrics.responses4xx+metrics.responses5xx;return {...metrics,avgResponseMs:handled?+(metrics.totalResponseMs/handled).toFixed(1):0,uptimeSeconds:Math.floor((Date.now()-STARTED_AT)/1000)}}
if(IS_PROD&&(SECRET==='dev-only-change-before-production'||SECRET.length<32)){console.error('ZOVRO_SECRET must be at least 32 characters in production.');process.exit(1)}
if(IS_PROD&&OPS_TOKEN.length<24){console.error('ZOVRO_OPS_TOKEN must be at least 24 characters in production.');process.exit(1)}
if(IS_PROD&&!ALLOWED_ORIGINS.size){console.error('ZOVRO_ALLOWED_ORIGINS is required in production.');process.exit(1)}
fs.mkdirSync(DATA,{recursive:true});
const BASE_SECURITY_HEADERS={'x-content-type-options':'nosniff','referrer-policy':'no-referrer','x-frame-options':'DENY','permissions-policy':'geolocation=(self), camera=(), microphone=()','cross-origin-opener-policy':'same-origin','cross-origin-resource-policy':'same-origin'};
const json=(res,code,obj,extra={})=>{res.writeHead(code,{'content-type':'application/json; charset=utf-8','cache-control':'no-store',...BASE_SECURITY_HEADERS,...extra});res.end(JSON.stringify(obj))};
const body=req=>new Promise((resolve,reject)=>{let s='',bytes=0,tooLarge=false;req.on('data',c=>{bytes+=c.length;if(bytes>1e6){tooLarge=true;s='';return}if(!tooLarge)s+=c});req.on('end',()=>{if(tooLarge){const e=new Error('Body too large');e.code='BODY_TOO_LARGE';return reject(e)}try{resolve(s?JSON.parse(s):{})}catch(cause){const e=new Error('Invalid JSON');e.code='INVALID_JSON';e.cause=cause;reject(e)}});req.on('error',reject)});
const hash=p=>{const salt=crypto.randomBytes(16).toString('hex');return salt+':'+crypto.scryptSync(p,salt,64).toString('hex')};
const verify=(p,h)=>{try{const [salt,key]=h.split(':');const a=Buffer.from(key,'hex'),b=crypto.scryptSync(p,salt,64);return a.length===b.length&&crypto.timingSafeEqual(a,b)}catch{return false}};
const b64=o=>Buffer.from(JSON.stringify(o)).toString('base64url');
function token(u,db){const sid=crypto.randomUUID(),exp=Date.now()+86400000*7;db.deviceSessions=(db.deviceSessions||[]).filter(x=>x.expiresAt>Date.now());db.deviceSessions.push({id:sid,userId:u.id,createdAt:new Date().toISOString(),expiresAt:exp});const p=b64({uid:u.id,role:u.role,sid,exp});return p+'.'+crypto.createHmac('sha256',SECRET).update(p).digest('base64url')}
function auth(req){const t=(req.headers.authorization||'').replace(/^Bearer /,'');if(!t)return null;const [p,s]=t.split('.');if(!p||!s)return null;const x=crypto.createHmac('sha256',SECRET).update(p).digest('base64url');if(x.length!==s.length||!crypto.timingSafeEqual(Buffer.from(x),Buffer.from(s)))return null;try{const d=JSON.parse(Buffer.from(p,'base64url'));if(d.exp<=Date.now()||!d.sid)return null;const db=readDb(),session=(db.deviceSessions||[]).find(v=>v.id===d.sid&&v.userId===d.uid&&v.expiresAt>Date.now());return session?d:null}catch{return null}}
const safeUser=u=>({id:u.id,name:u.name,phone:u.phone,email:u.email,role:u.role,service:u.service||null,license:u.license||null,availability:u.availability!==false,accountStatus:u.accountStatus||'active',phoneVerified:!!u.phoneVerified,providerVerified:!!u.providerVerified});
function notify(db,userId,title,text,meta={}){if(!userId)return;db.notifications.unshift({id:crypto.randomUUID(),userId,title:String(title).slice(0,120),text:String(text).slice(0,500),meta,read:false,createdAt:new Date().toISOString()});db.notifications=db.notifications.slice(0,5000)}
function audit(db,user,action,meta={}){db.audit.unshift({id:crypto.randomUUID(),user:user?.uid||null,action,meta,at:new Date().toISOString()});db.audit=db.audit.slice(0,1000)}
function canAccess(r,me){return r.customerId===me.uid||r.providerId===me.uid||(me.role==='provider'&&!r.providerId)}
const attempts=new Map();
function clientIp(req){const forwarded=String(req.headers['x-forwarded-for']||'').split(',')[0].trim();return forwarded||req.socket.remoteAddress||'local'}
function limited(req,key,limit=20,windowMs=60000){const now=Date.now(),k=clientIp(req)+':'+key,a=attempts.get(k)||[];const fresh=a.filter(t=>now-t<windowMs);fresh.push(now);if(fresh.length>limit)attempts.set(k,fresh.slice(-limit));else attempts.set(k,fresh);if(attempts.size>5000)for(const [ak,av] of attempts)if(!av.some(t=>now-t<windowMs))attempts.delete(ak);return fresh.length>limit}
const cleanPhone=v=>String(v||'').replace(/[^0-9+]/g,'').slice(0,30);
const validPhone=v=>/^\+?[0-9]{7,15}$/.test(v);
const validEmail=v=>!v||/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(v);
const validPassword=v=>typeof v==='string'&&v.length>=10&&v.length<=128&&/[A-Za-z]/.test(v)&&/[0-9]/.test(v);
const locationFresh=l=>l&&Date.now()-Date.parse(l.updatedAt||0)<=15*60*1000;
const milesBetween=(a,b,c,d)=>{const rad=x=>x*Math.PI/180,R=3958.8,dl=rad(c-a),dn=rad(d-b),q=Math.sin(dl/2)**2+Math.cos(rad(a))*Math.cos(rad(c))*Math.sin(dn/2)**2;return 2*R*Math.asin(Math.sqrt(q))};
function eligibleProviders(db,service,location,radiusMiles=25,excludedProviderIds=[]){const excluded=new Set(excludedProviderIds);return db.users.filter(u=>u.role==='provider'&&!excluded.has(u.id)&&(u.accountStatus||'active')==='active'&&u.availability!==false&&(!service||!u.service||u.service===service)).map(u=>{const l=db.providerLocations.find(x=>x.providerId===u.id),stats=providerStats(db,u.id);if(!location)return {user:u,location:l||null,distanceMiles:null,priorityScore:stats.dispatchPriorityScore};if(!locationFresh(l))return null;const d=milesBetween(location.lat,location.lng,l.lat,l.lng);return d<=radiusMiles?{user:u,location:l,distanceMiles:+d.toFixed(1),priorityScore:stats.dispatchPriorityScore}:null}).filter(Boolean).sort((a,b)=>(b.priorityScore-a.priorityScore)||((a.distanceMiles??9999)-(b.distanceMiles??9999)))}

function throttle(res,retryAfter=60){return json(res,429,{error:'Too many requests. Try again shortly.'},{'retry-after':String(retryAfter)})}
function requireActive(db,me,res){const u=db.users.find(x=>x.id===me.uid);if(!u)return json(res,404,{error:'User not found'});if((u.accountStatus||'active')!=='active'){json(res,403,{error:'Account is not active'});return null}return u}
function providerStats(db,providerId){const jobs=(db.requests||[]).filter(r=>r.providerId===providerId||r.completedProviderId===providerId),completed=jobs.filter(r=>r.status==='Completed'&&r.completedProviderId===providerId),ratings=(db.ratings||[]).filter(x=>x.providerId===providerId),avg=ratings.length?ratings.reduce((n,x)=>n+Number(x.stars||0),0)/ratings.length:null,auditRows=db.audit||[],providerCancelled=auditRows.filter(a=>a.user===providerId&&a.action==='request.cancel'&&a.meta?.cancelledBy==='provider').length,emergencyHandoffs=auditRows.filter(a=>a.user===providerId&&a.action==='request.emergency_handoff').length,attempts=completed.length+providerCancelled+emergencyHandoffs,completionRate=attempts?Math.round(completed.length/attempts*100):null,emergencyPenalty=emergencyHandoffs?2+Math.max(0,emergencyHandoffs-1)*8:0,reliabilityScore=Math.max(0,Math.min(100,Math.round(100-providerCancelled*8-emergencyPenalty))),ratingScore=avg===null?80:avg*20,completionScore=completionRate===null?80:completionRate,dispatchPriorityScore=Math.max(0,Math.min(100,Math.round(reliabilityScore*.55+ratingScore*.3+completionScore*.15))),professionalLevel=reliabilityScore>=90?'Excellent':reliabilityScore>=75?'Good':reliabilityScore>=60?'Needs improvement':'Low';return {completedJobs:completed.length,rating:avg===null?null:+avg.toFixed(1),ratingCount:ratings.length,providerCancellations:providerCancelled,emergencyHandoffs,completionRate,reliabilityScore,dispatchPriorityScore,professionalLevel}}
function requestView(r,db,viewer=null){const customer=db.users.find(u=>u.id===r.customerId),provider=db.users.find(u=>u.id===r.providerId),view={...r,customerName:customer?.name||'Customer',providerName:provider?.name||null,messages:(db.messages||[]).filter(m=>m.requestId===r.id)};if(viewer?.role==='provider'){delete view.lastHandoffReason;view.handoffs=(r.handoffs||[]).map(h=>({occurredAt:h.occurredAt,previousStatus:h.previousStatus}))}return view}
async function api(req,res,url){
 if(req.method==='GET'&&url.pathname==='/api/health')return json(res,200,{ok:true,service:'zovro-api',version:APP_VERSION,stage:STAGE,environment:IS_PROD?'production':'development',database:dbInfo().engine,uptimeSeconds:Math.floor((Date.now()-STARTED_AT)/1000),time:new Date().toISOString()});
 if(req.method==='GET'&&url.pathname==='/api/ready'){try{const info=dbInfo();readDb();if(info.mirrorMode!=='off'&&!info.postgresOperational)return json(res,503,{ready:false,service:'zovro-api',version:APP_VERSION,stage:STAGE,database:info.engine,mirrorMode:info.mirrorMode,postgresOperational:false,error:'PostgreSQL mirror is not operational',time:new Date().toISOString()});return json(res,200,{ready:true,service:'zovro-api',version:APP_VERSION,stage:STAGE,database:info.engine,mirrorMode:info.mirrorMode,postgresOperational:info.postgresOperational,time:new Date().toISOString()})}catch(e){metrics.errors++;metrics.lastErrorAt=new Date().toISOString();logEvent('error','readiness_failed',{message:e.message});return json(res,503,{ready:false,error:'Service not ready'})}}
 if(req.method==='GET'&&url.pathname==='/api/metrics'){if(!OPS_TOKEN||req.headers['x-zovro-ops-token']!==OPS_TOKEN)return json(res,404,{error:'Not found'});return json(res,200,{service:'zovro-api',version:APP_VERSION,stage:STAGE,metrics:metricsSnapshot()})}
 if(req.method==='POST'&&url.pathname==='/api/auth/register'){if(limited(req,'register',8,60000))return throttle(res);const b=await body(req),name=String(b.name||'').trim(),phone=cleanPhone(b.phone),email=String(b.email||'').trim().toLowerCase();if(name.length<2||name.length>80||!validPhone(phone)||!validPassword(b.password)||!validEmail(email))return json(res,400,{error:'Valid name, phone, email and strong password required (10+ chars with letters and numbers)'});const db=readDb();if(db.users.some(u=>u.phone===phone))return json(res,409,{error:'Phone already registered'});const u={id:crypto.randomUUID(),name,phone,email:email.slice(0,120),role:b.role==='provider'?'provider':'customer',service:b.service?String(b.service).trim().slice(0,80):null,license:b.license?String(b.license).trim().slice(0,80):null,accountStatus:'active',phoneVerified:false,providerVerified:false,passwordHash:hash(String(b.password)),createdAt:new Date().toISOString()};db.users.push(u);audit(db,{uid:u.id},'register',{role:u.role});const accessToken=token(u,db);writeDb(db);return json(res,201,{token:accessToken,user:safeUser(u)})}
 if(req.method==='POST'&&url.pathname==='/api/auth/login'){if(limited(req,'login',10,60000))return throttle(res);const b=await body(req),db=readDb(),u=db.users.find(x=>x.phone===cleanPhone(b.phone));if(!u||!verify(String(b.password||''),u.passwordHash))return json(res,401,{error:'Invalid credentials'});if((u.accountStatus||'active')!=='active')return json(res,403,{error:'Account is not active'});audit(db,{uid:u.id},'login');const accessToken=token(u,db);writeDb(db);return json(res,200,{token:accessToken,user:safeUser(u)})}
 const me=auth(req);if(!me)return json(res,401,{error:'Authentication required'});
 if(req.method==='POST'&&url.pathname==='/api/auth/logout'){const db=readDb();db.deviceSessions=(db.deviceSessions||[]).filter(x=>x.id!==me.sid);audit(db,me,'logout');writeDb(db);return json(res,200,{ok:true})}
 if(req.method==='GET'&&url.pathname==='/api/auth/sessions'){const db=readDb(),u=requireActive(db,me,res);if(!u)return;const sessions=(db.deviceSessions||[]).filter(x=>x.userId===me.uid&&x.expiresAt>Date.now()).map(x=>({id:x.id,current:x.id===me.sid,createdAt:x.createdAt,expiresAt:new Date(x.expiresAt).toISOString()}));return json(res,200,{sessions})}
 if(req.method==='DELETE'&&url.pathname==='/api/auth/sessions/others'){const db=readDb(),u=requireActive(db,me,res);if(!u)return;const before=(db.deviceSessions||[]).filter(x=>x.userId===me.uid).length;db.deviceSessions=(db.deviceSessions||[]).filter(x=>x.userId!==me.uid||x.id===me.sid);audit(db,me,'sessions.revoke_others',{revoked:Math.max(0,before-1)});writeDb(db);return json(res,200,{ok:true,revoked:Math.max(0,before-1)})}
 if(req.method==='POST'&&url.pathname==='/api/auth/password'){if(limited(req,'password-change',6,60000))return throttle(res);const b=await body(req),db=readDb(),u=requireActive(db,me,res);if(!u)return;if(!verify(String(b.currentPassword||''),u.passwordHash))return json(res,401,{error:'Current password is incorrect'});if(!validPassword(b.newPassword))return json(res,400,{error:'New password must be 10-128 characters and include letters and numbers'});if(verify(String(b.newPassword),u.passwordHash))return json(res,400,{error:'New password must be different'});u.passwordHash=hash(String(b.newPassword));db.deviceSessions=(db.deviceSessions||[]).filter(x=>x.userId!==me.uid||x.id===me.sid);audit(db,me,'password.change',{otherSessionsRevoked:true});writeDb(db);return json(res,200,{ok:true,otherSessionsRevoked:true})}
 if(req.method==='GET'&&url.pathname==='/api/notifications'){const db=readDb(),since=String(url.searchParams.get('since')||'');let rows=db.notifications.filter(n=>n.userId===me.uid);if(since)rows=rows.filter(n=>n.createdAt>since);return json(res,200,{notifications:rows.slice(0,100),serverTime:new Date().toISOString()})}
 if(req.method==='POST'&&url.pathname==='/api/notifications/read'){const db=readDb();for(const n of db.notifications)if(n.userId===me.uid)n.read=true;writeDb(db);return json(res,200,{ok:true})}
 if(req.method==='GET'&&url.pathname==='/api/me'){const u=readDb().users.find(x=>x.id===me.uid);return u?json(res,200,{user:safeUser(u)}):json(res,404,{error:'User not found'})}
 if(req.method==='PATCH'&&url.pathname==='/api/me'){const b=await body(req),db=readDb(),u=requireActive(db,me,res);if(!u)return;if(b.name)u.name=String(b.name).trim().slice(0,80);if(b.email!==undefined)u.email=String(b.email||'').trim().slice(0,120);if(u.role==='provider'&&b.service)u.service=String(b.service).slice(0,80);audit(db,me,'profile.update');writeDb(db);return json(res,200,{user:safeUser(u)})}
 if(req.method==='DELETE'&&url.pathname==='/api/me'){const b=await body(req);if(b.confirm!=='DELETE')return json(res,400,{error:'Deletion confirmation required'});const db=readDb(),u=db.users.find(x=>x.id===me.uid);if(!u)return json(res,404,{error:'User not found'});const uid=u.id,wasProvider=u.role==='provider';for(const r of db.requests){if(r.status==='Completed')continue;if(r.customerId===uid){r.status='Cancelled';r.updatedAt=new Date().toISOString()}if(r.providerId===uid){r.providerId=null;r.providerName=null;r.status='Looking for providers';r.updatedAt=new Date().toISOString()}}db.providerLocations=(db.providerLocations||[]).filter(x=>x.providerId!==uid);db.notifications=(db.notifications||[]).filter(x=>x.userId!==uid);db.verificationRequests=(db.verificationRequests||[]).filter(x=>x.providerId!==uid);db.deviceSessions=(db.deviceSessions||[]).filter(x=>x.userId!==uid);u.name='Deleted user';u.phone='deleted-'+uid.slice(0,8);u.email='';u.service=null;u.license=null;u.availability=false;u.accountStatus='deleted';u.phoneVerified=false;u.providerVerified=false;u.passwordHash='deleted';u.deletedAt=new Date().toISOString();audit(db,{uid},'account.delete',{role:wasProvider?'provider':'customer'});writeDb(db);return json(res,200,{ok:true,deleted:true})}

 if(req.method==='POST'&&url.pathname==='/api/provider/verification'){const db=readDb(),u=requireActive(db,me,res);if(!u)return;if(u.role!=='provider')return json(res,403,{error:'Provider role required'});const b=await body(req);if(!b.licenseNumber&&!b.note)return json(res,400,{error:'License number or verification note required'});const existing=db.verificationRequests.find(v=>v.providerId===u.id&&v.status==='pending');if(existing)return json(res,409,{error:'Verification already pending'});const v={id:crypto.randomUUID(),providerId:u.id,licenseNumber:String(b.licenseNumber||'').slice(0,80),note:String(b.note||'').slice(0,500),status:'pending',createdAt:new Date().toISOString()};db.verificationRequests.unshift(v);audit(db,me,'provider.verification.submit',{verificationId:v.id});writeDb(db);return json(res,201,{verification:v})}
 if(req.method==='GET'&&url.pathname==='/api/provider/verification'){const db=readDb(),u=requireActive(db,me,res);if(!u)return;const rows=db.verificationRequests.filter(v=>v.providerId===u.id);return json(res,200,{verification:rows[0]||null,providerVerified:!!u.providerVerified})}
 if(req.method==='GET'&&url.pathname==='/api/admin/overview'){const db=readDb(),u=requireActive(db,me,res);if(!u)return;if(u.role!=='admin')return json(res,403,{error:'Admin role required'});return json(res,200,{users:db.users.length,customers:db.users.filter(x=>x.role==='customer').length,providers:db.users.filter(x=>x.role==='provider').length,openRequests:db.requests.filter(r=>r.status!=='Completed').length,completedRequests:db.requests.filter(r=>r.status==='Completed').length,pendingVerifications:db.verificationRequests.filter(v=>v.status==='pending').length})}
 if(req.method==='GET'&&url.pathname==='/api/admin/verifications'){const db=readDb(),u=requireActive(db,me,res);if(!u)return;if(u.role!=='admin')return json(res,403,{error:'Admin role required'});return json(res,200,{verifications:db.verificationRequests.map(v=>({...v,provider:safeUser(db.users.find(x=>x.id===v.providerId)||{})}))})}
 const verifyRoute=url.pathname.match(/^\/api\/admin\/verifications\/([^/]+)$/);if(req.method==='POST'&&verifyRoute){const db=readDb(),u=requireActive(db,me,res);if(!u)return;if(u.role!=='admin')return json(res,403,{error:'Admin role required'});const b=await body(req),v=db.verificationRequests.find(x=>x.id===verifyRoute[1]);if(!v)return json(res,404,{error:'Verification not found'});if(!['approved','rejected'].includes(b.status))return json(res,400,{error:'Status must be approved or rejected'});v.status=b.status;v.reviewedAt=new Date().toISOString();v.reviewedBy=u.id;const provider=db.users.find(x=>x.id===v.providerId);if(provider){provider.providerVerified=b.status==='approved';notify(db,provider.id,'Verification '+b.status,'Your ZOVRO provider verification was '+b.status+'.',{verificationId:v.id})}audit(db,me,'provider.verification.review',{verificationId:v.id,status:v.status});writeDb(db);return json(res,200,{verification:v})}
 if(req.method==='PATCH'&&url.pathname==='/api/provider/availability'){const b=await body(req),db=readDb(),u=requireActive(db,me,res);if(!u)return;if(u.role!=='provider')return json(res,403,{error:'Provider role required'});u.availability=!!b.available;audit(db,me,'provider.availability',{available:u.availability});writeDb(db);return json(res,200,{user:safeUser(u)})}
 if(req.method==='POST'&&url.pathname==='/api/provider/location'){const b=await body(req),db=readDb(),u=requireActive(db,me,res);if(!u)return;if(u.role!=='provider')return json(res,403,{error:'Provider role required'});const lat=+b.lat,lng=+b.lng;if(!Number.isFinite(lat)||!Number.isFinite(lng)||Math.abs(lat)>90||Math.abs(lng)>180)return json(res,400,{error:'Valid coordinates required'});db.providerLocations=db.providerLocations.filter(x=>x.providerId!==u.id);db.providerLocations.push({providerId:u.id,lat,lng,accuracy:Number.isFinite(+b.accuracy)?+b.accuracy:null,updatedAt:new Date().toISOString()});writeDb(db);return json(res,200,{ok:true})}
 const providerProfile=url.pathname.match(/^\/api\/providers\/([^/]+)\/profile$/);if(req.method==='GET'&&providerProfile){const db=readDb(),u=db.users.find(x=>x.id===providerProfile[1]&&x.role==='provider'&&(x.accountStatus||'active')==='active');if(!u)return json(res,404,{error:'Provider not found'});const publicProvider=safeUser(u);delete publicProvider.phone;delete publicProvider.email;return json(res,200,{provider:{...publicProvider,stats:providerStats(db,u.id)}})}
 if(req.method==='GET'&&url.pathname==='/api/providers/nearby'){const db=readDb(),lat=+url.searchParams.get('lat'),lng=+url.searchParams.get('lng'),service=String(url.searchParams.get('service')||''),radius=Math.min(50,Math.max(1,+url.searchParams.get('radius')||25));if(!Number.isFinite(lat)||!Number.isFinite(lng))return json(res,400,{error:'lat and lng required'});const rows=eligibleProviders(db,service,{lat,lng},radius).slice(0,20).map(x=>({provider:{...safeUser(x.user),stats:providerStats(db,x.user.id)},distanceMiles:x.distanceMiles,etaMinutes:Math.max(5,Math.round(x.distanceMiles*3+5)),locationUpdatedAt:x.location.updatedAt}));return json(res,200,{providers:rows,radiusMiles:radius,locationFreshnessMinutes:15})}
 const track=url.pathname.match(/^\/api\/requests\/([^/]+)\/tracking$/);if(req.method==='GET'&&track){const db=readDb(),r=db.requests.find(x=>x.id===track[1]);if(!r||!(r.customerId===me.uid||r.providerId===me.uid))return json(res,404,{error:'Request not found'});const l=r.providerId?db.providerLocations.find(x=>x.providerId===r.providerId):null;return json(res,200,{requestId:r.id,status:r.status,customerLocation:r.location||null,providerLocation:l||null})}
 if(req.method==='GET'&&url.pathname==='/api/requests'){const db=readDb();let rows=me.role==='provider'?db.requests.filter(r=>!r.providerId||r.providerId===me.uid):db.requests.filter(r=>r.customerId===me.uid);return json(res,200,{requests:rows.map(r=>requestView(r,db,me))})}
 if(req.method==='POST'&&url.pathname==='/api/requests'){if(me.role!=='customer')return json(res,403,{error:'Customer role required'});if(limited(req,'request.create:'+me.uid,12,60000))return throttle(res);const b=await body(req);if(!b.service||!b.details)return json(res,400,{error:'Service and details required'});const db=readDb();const user=requireActive(db,me,res);if(!user)return;
 const sos=b.source==='sos';
 if(sos){
  if(b.service!=='Roadside Assistance'||b.urgent!==true||typeof b.clientRequestId!=='string'||!/^[a-zA-Z0-9-]{16,80}$/.test(b.clientRequestId))return json(res,400,{error:'Valid SOS request identity and roadside service required'});
  const previous=db.requests.find(r=>r.customerId===me.uid&&r.source==='sos'&&r.clientRequestId===b.clientRequestId);
  const active=db.requests.find(r=>r.customerId===me.uid&&r.source==='sos'&&!['Completed','Cancelled'].includes(r.status));
  const existing=previous||active;
  if(existing)return json(res,200,{request:requestView(existing,db,me),reused:true,dispatch:{urgent:true,notifiedProviders:0,radiusMiles:15}});
 }
 const loc=b.location;
 if(loc!=null&&(typeof loc.lat!=='number'||typeof loc.lng!=='number'||!Number.isFinite(loc.lat)||!Number.isFinite(loc.lng)||Math.abs(loc.lat)>90||Math.abs(loc.lng)>180))return json(res,400,{error:'Valid coordinates required'});
 if(sos&&(!loc||typeof loc.accuracy!=='number'||!Number.isFinite(loc.accuracy)||loc.accuracy<0||loc.accuracy>1000||typeof loc.capturedAt!=='string'||!Number.isFinite(Date.parse(loc.capturedAt))||Date.now()-Date.parse(loc.capturedAt)>120000||Date.parse(loc.capturedAt)-Date.now()>30000))return json(res,400,{error:'SOS requires a recent, precise location. Refresh location and try again.'});
 const urgent=!!b.urgent,r={id:crypto.randomUUID(),customerId:me.uid,service:String(b.service).slice(0,80),details:String(b.details).slice(0,1000),address:String(b.address||'').slice(0,200),time:String(b.time||'As soon as possible').slice(0,80),pricing:String(b.pricing||'Get provider offers').slice(0,80),urgent,location:b.location&&Number.isFinite(+b.location.lat)&&Number.isFinite(+b.location.lng)?{lat:+b.location.lat,lng:+b.location.lng}:null,status:'Looking for providers',providerId:null,createdAt:new Date().toISOString()};if(sos){r.source='sos';r.clientRequestId=b.clientRequestId;r.location.accuracy=loc.accuracy;r.location.capturedAt=loc.capturedAt}db.requests.unshift(r);const candidates=eligibleProviders(db,r.service,r.location,urgent?15:25).slice(0,urgent?12:20);for(const x of candidates)notify(db,x.user.id,urgent?'URGENT nearby request':'New nearby service request',r.service+': '+r.details.slice(0,120),{requestId:r.id,type:urgent?'urgent_request':'new_request',distanceMiles:x.distanceMiles});audit(db,me,'request.create',{requestId:r.id,urgent,notifiedProviders:candidates.length});writeDb(db);return json(res,201,{request:requestView(r,db,me),dispatch:{urgent,notifiedProviders:candidates.length,radiusMiles:urgent?15:25}})}
 const accept=url.pathname.match(/^\/api\/requests\/([^/]+)\/accept$/);if(req.method==='POST'&&accept){if(me.role!=='provider')return json(res,403,{error:'Provider role required'});const db=readDb(),r=db.requests.find(x=>x.id===accept[1]);if(!r)return json(res,404,{error:'Request not found'});if(['Completed','Cancelled'].includes(r.status))return json(res,409,{error:'Request is no longer available'});if(r.providerId&&r.providerId!==me.uid)return json(res,409,{error:'Request already accepted'});if((r.handoffs||[]).some(h=>h.fromProviderId===me.uid))return json(res,409,{error:'You handed off this request and cannot accept it again'});r.providerId=me.uid;r.status='Accepted';r.acceptedAt=new Date().toISOString();db.messages.push({id:crypto.randomUUID(),requestId:r.id,userId:me.uid,from:'provider',text:'I accepted your request and will keep you updated here.',createdAt:new Date().toISOString()});notify(db,r.customerId,'Provider accepted your request',(db.users.find(x=>x.id===me.uid)?.name||'A provider')+' accepted your '+r.service+' request.',{requestId:r.id,type:'accepted'});audit(db,me,'request.accept',{requestId:r.id});writeDb(db);return json(res,200,{request:requestView(r,db,me)})}
 const emergencyHandoff=url.pathname.match(/^\/api\/requests\/([^/]+)\/provider-emergency-handoff$/);if(req.method==='POST'&&emergencyHandoff){if(me.role!=='provider')return json(res,403,{error:'Provider role required'});if(limited(req,'provider.emergency_handoff:'+me.uid,3,60*60*1000))return throttle(res,3600);const b=await body(req),reason=String(b.reason||'').trim();if(reason.length<8||reason.length>300)return json(res,400,{error:'Emergency reason must be 8-300 characters'});const db=readDb(),r=db.requests.find(x=>x.id===emergencyHandoff[1]&&x.providerId===me.uid);if(!r)return json(res,404,{error:'Assigned request not found'});if(!['Accepted','On the way'].includes(r.status))return json(res,409,{error:'Emergency handoff is only available before arrival'});const provider=db.users.find(x=>x.id===me.uid),at=new Date().toISOString(),handoff={id:crypto.randomUUID(),fromProviderId:me.uid,fromProviderName:provider?.name||'Provider',reason:reason.slice(0,300),previousStatus:r.status,occurredAt:at};r.handoffs=r.handoffs||[];r.handoffs.push(handoff);r.reassignmentCount=r.handoffs.length;r.lastHandoffAt=at;r.lastHandoffReason=handoff.reason;r.providerId=null;r.providerName=null;r.status='Looking for replacement';r.updatedAt=at;db.messages.push({id:crypto.randomUUID(),requestId:r.id,userId:me.uid,from:'provider',text:'The assigned provider reported an emergency. ZOVRO is finding a replacement now.',createdAt:at});notify(db,r.customerId,'We are finding a replacement provider',r.service+': '+handoff.reason,{requestId:r.id,type:'emergency_handoff',reassignmentCount:r.reassignmentCount});audit(db,me,'request.emergency_handoff',{requestId:r.id,reason:handoff.reason,reassignmentCount:r.reassignmentCount});const excluded=r.handoffs.map(h=>h.fromProviderId),radius=r.urgent?15:25,candidates=eligibleProviders(db,r.service,r.location,radius,excluded).slice(0,r.urgent?12:20);for(const x of candidates)notify(db,x.user.id,r.urgent?'URGENT replacement needed':'Replacement provider needed',r.service+': '+r.details.slice(0,120),{requestId:r.id,type:'replacement_request',distanceMiles:x.distanceMiles,priorityScore:x.priorityScore});const impact=providerStats(db,me.uid);writeDb(db);return json(res,200,{request:requestView(r,db,me),dispatch:{urgent:!!r.urgent,notifiedProviders:candidates.length,radiusMiles:radius},providerImpact:impact})}
 const cancel=url.pathname.match(/^\/api\/requests\/([^/]+)\/cancel$/);if(req.method==='POST'&&cancel){const b=await body(req),db=readDb(),r=db.requests.find(x=>x.id===cancel[1]);if(!r)return json(res,404,{error:'Request not found'});const isCustomer=r.customerId===me.uid,isProvider=r.providerId===me.uid;if(!isCustomer&&!isProvider)return json(res,403,{error:'Not allowed'});if(['Completed','Cancelled'].includes(r.status))return json(res,409,{error:'Request cannot be cancelled'});if(isProvider&&['Arrived','In progress'].includes(r.status))return json(res,409,{error:'Provider cannot cancel after arrival; contact support'});const actor=isCustomer?'customer':'provider',reason=String(b.reason||'Cancelled by '+actor).trim().slice(0,300),providerId=r.providerId;r.status='Cancelled';r.cancelledAt=new Date().toISOString();r.cancelledBy=actor;r.cancelReason=reason;if(isProvider){r.providerId=null;r.providerName=null}db.messages.push({id:crypto.randomUUID(),requestId:r.id,userId:me.uid,from:me.role,text:'Request cancelled: '+reason,createdAt:r.cancelledAt});const other=isCustomer?providerId:r.customerId;notify(db,other,'Request cancelled',r.service+': '+reason,{requestId:r.id,type:'cancelled',cancelledBy:actor});audit(db,me,'request.cancel',{requestId:r.id,cancelledBy:actor,reason});writeDb(db);return json(res,200,{request:requestView(r,db,me)})}
 const msg=url.pathname.match(/^\/api\/requests\/([^/]+)\/messages$/);if(msg){const db=readDb(),r=db.requests.find(x=>x.id===msg[1]);if(!r||!canAccess(r,me))return json(res,404,{error:'Request not found'});if(req.method==='GET')return json(res,200,{messages:(db.messages||[]).filter(m=>m.requestId===r.id)});if(req.method==='POST'){if(limited(req,'message:'+me.uid,30,60000))return throttle(res);const b=await body(req);if(!String(b.text||'').trim())return json(res,400,{error:'Message required'});const m={id:crypto.randomUUID(),requestId:r.id,userId:me.uid,from:me.role,text:String(b.text).trim().slice(0,1500),createdAt:new Date().toISOString()};db.messages.push(m);const other=me.uid===r.customerId?r.providerId:r.customerId;notify(db,other,'New message',String(b.text).trim().slice(0,140),{requestId:r.id,type:'message'});audit(db,me,'message.send',{requestId:r.id});writeDb(db);return json(res,201,{message:m})}}
 const status=url.pathname.match(/^\/api\/requests\/([^/]+)\/status$/);if(req.method==='POST'&&status){if(me.role!=='provider')return json(res,403,{error:'Provider role required'});const allowed=['Accepted','On the way','Arrived','In progress','Completed'],b=await body(req),db=readDb(),r=db.requests.find(x=>x.id===status[1]&&x.providerId===me.uid);if(!r)return json(res,404,{error:'Assigned request not found'});if(r.status==='Cancelled'||r.status==='Completed')return json(res,409,{error:'Request lifecycle is closed'});if(!allowed.includes(b.status))return json(res,400,{error:'Invalid status'});const old=allowed.indexOf(r.status),next=allowed.indexOf(b.status);if(next<old||next>old+1)return json(res,409,{error:'Status must advance one step'});r.status=b.status;r.updatedAt=new Date().toISOString();if(r.status==='On the way')r.onTheWayAt=r.updatedAt;if(r.status==='Arrived')r.arrivedAt=r.updatedAt;if(r.status==='Completed'){r.completedProviderId=me.uid;r.completedAt=r.updatedAt}db.messages.push({id:crypto.randomUUID(),requestId:r.id,userId:me.uid,from:'provider',text:r.status==='Completed'?'The service is complete. Thank you for using ZOVRO.':'Status update: '+r.status+'.',createdAt:new Date().toISOString()});notify(db,r.customerId,'Job status updated',r.service+': '+r.status,{requestId:r.id,type:'status'});audit(db,me,'request.status',{requestId:r.id,status:r.status});writeDb(db);return json(res,200,{request:requestView(r,db,me)})}
 const rate=url.pathname.match(/^\/api\/requests\/([^/]+)\/rating$/);if(req.method==='POST'&&rate){if(me.role!=='customer')return json(res,403,{error:'Customer role required'});const b=await body(req),stars=Number(b.stars),db=readDb(),r=db.requests.find(x=>x.id===rate[1]&&x.customerId===me.uid&&x.status==='Completed');if(!r)return json(res,404,{error:'Completed request not found'});if(!Number.isInteger(stars)||stars<1||stars>5)return json(res,400,{error:'Rating must be 1-5'});r.rating=stars;r.ratedAt=new Date().toISOString();db.ratings=db.ratings||[];db.ratings.push({id:crypto.randomUUID(),requestId:r.id,providerId:r.providerId,customerId:me.uid,stars,createdAt:r.ratedAt});audit(db,me,'request.rate',{requestId:r.id,stars});writeDb(db);return json(res,200,{request:requestView(r,db,me)})}
 return json(res,404,{error:'API route not found'});
}
function securityHeaders(){return {...BASE_SECURITY_HEADERS,'content-security-policy':"default-src 'self'; style-src 'self' 'unsafe-inline'; script-src 'self' 'unsafe-inline'; img-src 'self' data:; connect-src 'self'"}}
function staticFile(req,res,url){let rel=url.pathname==='/'?'index.html':decodeURIComponent(url.pathname.slice(1));if(rel.includes('..'))return json(res,400,{error:'Bad path'});const f=path.join(ROOT,rel);if(!f.startsWith(ROOT)||!fs.existsSync(f)||fs.statSync(f).isDirectory())return json(res,404,{error:'Not found'});const ext=path.extname(f);const types={'.html':'text/html; charset=utf-8','.js':'text/javascript; charset=utf-8','.css':'text/css; charset=utf-8','.json':'application/json; charset=utf-8','.png':'image/png','.svg':'image/svg+xml'};res.writeHead(200,{'content-type':types[ext]||'application/octet-stream',...securityHeaders()});fs.createReadStream(f).pipe(res)}
const server=http.createServer(async(req,res)=>{const requestId=crypto.randomUUID(),started=Date.now();metrics.requests++;res.setHeader('x-request-id',requestId);res.on('finish',()=>{const ms=Date.now()-started;metrics.totalResponseMs+=ms;if(res.statusCode>=500)metrics.responses5xx++;else if(res.statusCode>=400)metrics.responses4xx++;else if(res.statusCode>=200)metrics.responses2xx++;logEvent(res.statusCode>=500?'error':'info','http_request',{requestId,method:req.method,path:String(req.url||'').split('?')[0],status:res.statusCode,durationMs:ms,ip:clientIp(req)})});const origin=req.headers.origin;if(IS_PROD&&origin&&!ALLOWED_ORIGINS.has(origin))return json(res,403,{error:'Origin not allowed'});if(origin&&ALLOWED_ORIGINS.has(origin)){res.setHeader('access-control-allow-origin',origin);res.setHeader('vary','Origin');res.setHeader('access-control-allow-headers','authorization, content-type, x-zovro-ops-token');res.setHeader('access-control-allow-methods','GET,POST,PATCH,DELETE,OPTIONS')}if(req.method==='OPTIONS'){res.writeHead(204);return res.end()}const url=new URL(req.url,'http://localhost');try{if(url.pathname.startsWith('/api/'))return await api(req,res,url);return staticFile(req,res,url)}catch(e){metrics.errors++;metrics.lastErrorAt=new Date().toISOString();logEvent(e.code==='INVALID_JSON'?'info':'error','request_failed',{requestId,method:req.method,path:url.pathname,message:e.message,stack:IS_PROD?undefined:e.stack});if(res.headersSent){res.destroy();return}if(e.code==='BODY_TOO_LARGE')return json(res,413,{error:'Request too large',requestId});if(e.code==='INVALID_JSON')return json(res,400,{error:'Invalid JSON',requestId});return json(res,500,{error:'Server error',requestId})}});
server.on('clientError',(err,socket)=>{metrics.errors++;metrics.lastErrorAt=new Date().toISOString();logEvent('error','client_error',{message:err.message});if(socket.writable)socket.end('HTTP/1.1 400 Bad Request\r\nConnection: close\r\n\r\n')});
process.on('unhandledRejection',reason=>{metrics.errors++;metrics.lastErrorAt=new Date().toISOString();logEvent('error','unhandled_rejection',{message:reason instanceof Error?reason.message:String(reason)})});
process.on('uncaughtException',err=>{metrics.errors++;metrics.lastErrorAt=new Date().toISOString();logEvent('error','uncaught_exception',{message:err.message});setTimeout(()=>process.exit(1),50)});
let shuttingDown=false;
function shutdown(signal){if(shuttingDown)return;shuttingDown=true;logEvent('info','shutdown_started',{signal});const force=setTimeout(()=>{logEvent('error','shutdown_forced',{signal});process.exit(1)},8000);force.unref();server.close(()=>{try{closeDb()}catch(e){logEvent('error','database_close_failed',{message:e.message})}clearTimeout(force);logEvent('info','shutdown_complete',{signal});process.exit(0)});}
process.on('SIGTERM',()=>shutdown('SIGTERM'));
process.on('SIGINT',()=>shutdown('SIGINT'));
server.listen(PORT,()=>logEvent('info','server_started',{port:PORT,environment:IS_PROD?'production':'development'}));

