'use strict';
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
const root=path.resolve(__dirname,'..');
const read=p=>fs.readFileSync(path.join(root,p),'utf8');
const pkg=JSON.parse(read('package.json'));
assert.equal(pkg.dependencies['@aparajita/capacitor-biometric-auth'],'9.1.2','Capacitor 7 biometric plugin must stay pinned to 9.1.2');
const bio=read('biometric-client.js');
const session=read('secure-session.js');
const prep=read('scripts/prepare-mobile.js');
const native=read('scripts/patch-native.js');
assert.match(bio,/ZOVRO never receives or stores your face or fingerprint data/,'Biometric privacy disclosure missing');
assert.match(bio,/allowDeviceCredential:true/,'Device credential fallback must remain enabled');
assert.match(bio,/setEnabled\(true\)/,'Biometric enable flow missing');
assert.match(session,/ZOVRO_BIOMETRIC\?\.shouldProtect/,'Saved-session biometric gate missing');
assert.ok(session.indexOf("ZOVRO_BIOMETRIC.authenticate('Unlock your ZOVRO account')")<session.indexOf('setRuntime(saved)'),'Saved session must not enter runtime before biometric authentication');
assert.match(prep,/biometric-client\.js/,'Biometric client must be included in mobile bundle');
assert.ok(prep.indexOf('<script src="biometric-client.js"></script>')<prep.indexOf('<script src="secure-session.js"></script>'),'Biometric client must load before secure session restoration');
assert.match(native,/NSFaceIDUsageDescription/,'iOS Face ID usage description missing');
assert.match(native,/android\.permission\.USE_BIOMETRIC/,'Android biometric permission missing');
console.log('Biometric security: plugin pin, native permissions, privacy disclosure, device-credential fallback and pre-session authentication gate passed.');
