'use strict';
const SERVICE_CATALOG=[
{id:'auto-roadside',icon:'🚗',priority:1,launchPriority:true,label:{en:'Auto & Roadside',es:'Auto y asistencia vial'},services:[['roadside-assistance','Roadside Assistance','Asistencia vial',1],['mobile-mechanic','Mobile Mechanic','Mecánico móvil',1],['auto-diagnostics','Auto Diagnostics','Diagnóstico automotriz',0],['auto-electrician','Auto Electrician','Electricista automotriz',0],['tire-change','Tire Change','Cambio de llanta',1],['mobile-tire-service','Mobile Tire Service','Servicio móvil de llantas',1],['flat-tire-repair','Flat Tire Repair','Reparación de llanta pinchada',1],['jump-start','Jump Start','Arranque de batería',1],['battery-replacement','Battery Replacement','Reemplazo de batería',1],['fuel-delivery','Fuel Delivery','Entrega de combustible',1],['vehicle-lockout','Vehicle Lockout','Apertura de vehículo',1],['towing','Towing','Remolque',1],['windshield-repair','Windshield Repair / Replacement','Reparación / reemplazo de parabrisas',0],['mobile-detailing','Mobile Auto Detailing','Detallado móvil de autos',0],['motorcycle-assistance','Motorcycle Assistance','Asistencia para motocicletas',1]]},
{id:'home-services',icon:'🏠',priority:2,launchPriority:true,label:{en:'Home Services',es:'Servicios del hogar'},services:[['handyman','Handyman','Mantenimiento general',0],['plumbing','Plumbing','Plomería',1],['electrical','Electrical','Electricidad',1],['hvac','HVAC','Climatización HVAC',1],['appliance-repair','Appliance Repair','Reparación de electrodomésticos',0],['carpenter','Carpenter','Carpintero',0],['locksmith','Locksmith','Cerrajero',1],['garage-door','Garage Door Repair & Installation','Reparación e instalación de garaje',0],['painting','Painting','Pintura',0],['flooring','Flooring Installation & Repair','Instalación y reparación de pisos',0],['drywall','Drywall Repair','Reparación de drywall',0],['furniture-assembly','Furniture Assembly','Ensamblaje de muebles',0],['tv-mounting','TV Mounting','Instalación de TV',0],['smart-home','Smart Home Installation','Instalación de hogar inteligente',0],['doors-windows','Door & Window Repair','Reparación de puertas y ventanas',0]]},
{id:'emergency-sos',icon:'🚨',priority:3,launchPriority:true,label:{en:'Emergency / SOS',es:'Emergencia / SOS'},services:[['emergency-roadside','Emergency Roadside Assistance','Asistencia vial de emergencia',1],['emergency-mechanic','Emergency Mobile Mechanic','Mecánico móvil de emergencia',1],['emergency-towing','Emergency Towing','Remolque de emergencia',1],['emergency-plumber','Emergency Plumber','Plomero de emergencia',1],['emergency-electrician','Emergency Electrician','Electricista de emergencia',1],['emergency-locksmith','Emergency Locksmith','Cerrajero de emergencia',1],['emergency-hvac','Emergency HVAC','HVAC de emergencia',1],['water-damage','Water Damage Cleanup','Limpieza por daños de agua',1]]},
{id:'construction-property',icon:'🏗️',priority:4,label:{en:'Construction & Property',es:'Construcción y propiedad'},services:[['general-contractor','General Contractor','Contratista general',0],['roofing','Roofing','Techos',1],['concrete','Concrete','Concreto',0],['masonry','Masonry','Mampostería',0],['fence','Fence Installation & Repair','Instalación y reparación de cercas',0],['deck','Deck Installation & Repair','Instalación y reparación de terrazas',0],['insulation','Insulation','Aislamiento',0],['siding','Siding','Revestimiento exterior',0],['windows-doors','Windows & Doors','Ventanas y puertas',0],['glass','Glass Repair & Installation','Reparación e instalación de vidrio',0],['waterproofing','Waterproofing','Impermeabilización',1],['demolition','Demolition','Demolición',0],['property-maintenance','Property Maintenance','Mantenimiento de propiedades',0]]},
{id:'outdoor-seasonal',icon:'🌳',priority:5,label:{en:'Outdoor & Seasonal',es:'Exterior y temporada'},services:[['landscaping','Landscaping','Paisajismo',0],['lawn-mowing','Lawn Mowing','Corte de césped',0],['yard-cleanup','Yard Cleanup','Limpieza de jardín',0],['tree-service','Tree Service','Servicio de árboles',0],['sprinkler-repair','Sprinkler Repair','Reparación de riego',0],['gutter-cleaning','Gutter Cleaning','Limpieza de canaletas',0],['pressure-washing','Pressure Washing','Lavado a presión',0],['leaf-removal','Leaf Removal','Retiro de hojas',0],['snow-removal','Snow Removal','Retiro de nieve',1],['snow-plowing','Snow Plowing','Arado de nieve',1],['ice-removal','Ice Removal','Retiro de hielo',1],['storm-cleanup','Storm Cleanup','Limpieza después de tormentas',1]]},
{id:'cleaning',icon:'🧹',priority:6,label:{en:'Cleaning',es:'Limpieza'},services:[['house-cleaning','House Cleaning','Limpieza de casas',0],['deep-cleaning','Deep Cleaning','Limpieza profunda',0],['move-in-cleaning','Move-In Cleaning','Limpieza de entrada',0],['move-out-cleaning','Move-Out Cleaning','Limpieza de salida',0],['carpet-cleaning','Carpet Cleaning','Limpieza de alfombras',0],['window-cleaning','Window Cleaning','Limpieza de ventanas',0],['commercial-cleaning','Commercial Cleaning','Limpieza comercial',0],['post-construction-cleaning','Post-Construction Cleaning','Limpieza post-construcción',0]]},
{id:'moving-hauling',icon:'🚚',priority:7,label:{en:'Moving & Hauling',es:'Mudanza y transporte'},services:[['moving','Moving','Mudanza',0],['furniture-moving','Furniture Moving','Mudanza de muebles',0],['loading-unloading','Loading & Unloading','Carga y descarga',0],['furniture-delivery','Furniture Delivery','Entrega de muebles',0],['appliance-delivery','Appliance Delivery','Entrega de electrodomésticos',0],['pickup-help','Pickup-Truck Help','Ayuda con camioneta pickup',0],['junk-removal','Junk Removal','Retiro de basura y objetos',0],['hauling','Hauling','Transporte de carga',0],['local-courier','Local Courier','Mensajería local',0]]},
{id:'business-services',icon:'🏢',priority:8,label:{en:'Business Services',es:'Servicios comerciales'},services:[['commercial-cleaning','Commercial Cleaning','Limpieza comercial',0],['commercial-hvac','Commercial HVAC','HVAC comercial',1],['commercial-plumbing','Commercial Plumbing','Plomería comercial',1],['commercial-electrical','Commercial Electrical','Electricidad comercial',1],['refrigeration-repair','Commercial Refrigeration Repair','Reparación de refrigeración comercial',1],['restaurant-equipment','Restaurant Equipment Repair','Reparación de equipos de restaurante',0],['security-cameras','Security Camera Installation','Instalación de cámaras de seguridad',0],['access-control','Access Control','Control de acceso',0],['sign-repair','Sign Installation & Repair','Instalación y reparación de letreros',0],['office-maintenance','Office & Store Maintenance','Mantenimiento de oficinas y tiendas',0]]},
{id:'other-help',icon:'✨',priority:99,label:{en:'Other / I Need Help',es:'Otro / Necesito ayuda'},services:[['other','Other / I Need Help','Otro / Necesito ayuda',0]]}
].map(c=>({...c,services:c.services.map(([id,en,es,urgentCapable])=>({id,label:{en,es},urgentCapable:!!urgentCapable,categoryId:c.id}))}));
const ALL_SERVICES=SERVICE_CATALOG.flatMap(c=>c.services);
const RULES=[['jump-start',['won\'t start','will not start','dead battery','battery dead','jump']],['flat-tire-repair',['flat tire','puncture','blowout']],['vehicle-lockout',['locked out','keys in car','car locked']],['fuel-delivery',['out of gas','no gas','need fuel']],['towing',['tow','towing','stuck vehicle']],['plumbing',['leak','leaking pipe','pipe burst','faucet','toilet']],['electrical',['no power','outlet','breaker','electrical']],['hvac',['no heat','no ac','air conditioner','furnace','hvac']],['garage-door',['garage door','garage won\'t open']],['roofing',['roof leak','roofing','shingles']],['water-damage',['water damage','flooded','basement flood']],['snow-removal',['snow','driveway snow']],['moving',['move furniture','moving house','need movers']],['junk-removal',['junk','old furniture removal','haul away']]];
function findServiceById(id){return ALL_SERVICES.find(s=>s.id===id)||null}
function smartMatch(text,{limit=5}={}){const q=String(text||'').trim().toLowerCase();if(!q)return[];const scored=[];for(const [id,terms] of RULES){const hit=terms.find(t=>q.includes(t));if(hit)scored.push({service:findServiceById(id),score:.95,matchedTerm:hit})}for(const s of ALL_SERVICES){if(s.id==='other')continue;const words=s.label.en.toLowerCase().split(/\W+/).filter(w=>w.length>3),n=words.filter(w=>q.includes(w)).length;if(n)scored.push({service:s,score:Math.min(.85,.55+n*.1),matchedTerm:null})}const seen=new Set();const out=scored.sort((a,b)=>b.score-a.score).filter(x=>x.service&&!seen.has(x.service.id)&&seen.add(x.service.id)).slice(0,limit);return out.length?out:[{service:findServiceById('other'),score:.2,matchedTerm:null}]}
function localizedLabel(item,lang='en'){return item?.label?.[lang]||item?.label?.en||''}
const api={SERVICE_CATALOG,ALL_SERVICES,findServiceById,smartMatch,localizedLabel};
if(typeof module!=='undefined'&&module.exports)module.exports=api;
if(typeof window!=='undefined')window.ZOVRO_CATALOG=api;
