'use strict';
(function(){
const SERVICE_CATALOG=[
{id:'auto-roadside',icon:'🚗',priority:1,launchPriority:true,label:{en:'Auto & Roadside',es:'Auto y asistencia vial'},services:[['roadside-assistance','Roadside Assistance','Asistencia vial',1],['mobile-mechanic','Mobile Mechanic','Mecánico móvil',1],['auto-diagnostics','Auto Diagnostics','Diagnóstico automotriz',0],['auto-electrician','Auto Electrician','Electricista automotriz',0],['tire-change','Tire Change','Cambio de llanta',1],['mobile-tire-service','Mobile Tire Service','Servicio móvil de llantas',1],['flat-tire-repair','Flat Tire Repair','Reparación de llanta pinchada',1],['jump-start','Jump Start','Arranque de batería',1],['battery-replacement','Battery Replacement','Reemplazo de batería',1],['fuel-delivery','Fuel Delivery','Entrega de combustible',1],['vehicle-lockout','Vehicle Lockout','Apertura de vehículo',1],['towing','Towing','Remolque',1],['windshield-repair','Windshield Repair / Replacement','Reparación / reemplazo de parabrisas',0],['mobile-detailing','Mobile Auto Detailing','Detallado móvil de autos',0],['motorcycle-assistance','Motorcycle Assistance','Asistencia para motocicletas',1]]},
{id:'home-services',icon:'🏠',priority:2,launchPriority:true,label:{en:'Home Services',es:'Servicios del hogar'},services:[['handyman','Handyman','Mantenimiento general',0],['plumbing','Plumbing','Plomería',1],['electrical','Electrical','Electricidad',1],['hvac','HVAC','Climatización HVAC',1],['appliance-repair','Appliance Repair','Reparación de electrodomésticos',0],['carpenter','Carpenter','Carpintero',0],['locksmith','Locksmith','Cerrajero',1],['garage-door','Garage Door Repair & Installation','Reparación e instalación de garaje',0],['painting','Painting','Pintura',0],['flooring','Flooring Installation & Repair','Instalación y reparación de pisos',0],['drywall','Drywall Repair','Reparación de drywall',0],['furniture-assembly','Furniture Assembly','Ensamblaje de muebles',0],['tv-mounting','TV Mounting','Instalación de TV',0],['smart-home','Smart Home Installation','Instalación de hogar inteligente',0],['doors-windows','Door & Window Repair','Reparación de puertas y ventanas',0]]},
{id:'emergency-sos',icon:'🚨',priority:3,launchPriority:true,label:{en:'Emergency / SOS',es:'Emergencia / SOS'},services:[['emergency-roadside','Emergency Roadside Assistance','Asistencia vial de emergencia',1],['emergency-mechanic','Emergency Mobile Mechanic','Mecánico móvil de emergencia',1],['emergency-towing','Emergency Towing','Remolque de emergencia',1],['emergency-plumber','Emergency Plumber','Plomero de emergencia',1],['emergency-electrician','Emergency Electrician','Electricista de emergencia',1],['emergency-locksmith','Emergency Locksmith','Cerrajero de emergencia',1],['emergency-hvac','Emergency HVAC','HVAC de emergencia',1],['water-damage','Water Damage Cleanup','Limpieza por daños de agua',1]]},
{id:'construction-property',icon:'🏗️',priority:4,label:{en:'Construction & Property',es:'Construcción y propiedad'},services:[['general-contractor','General Contractor','Contratista general',0],['roofing','Roofing','Techos',1],['concrete','Concrete','Concreto',0],['masonry','Masonry','Mampostería',0],['fence','Fence Installation & Repair','Instalación y reparación de cercas',0],['deck','Deck Installation & Repair','Instalación y reparación de terrazas',0],['insulation','Insulation','Aislamiento',0],['siding','Siding','Revestimiento exterior',0],['windows-doors','Windows & Doors','Ventanas y puertas',0],['glass','Glass Repair & Installation','Reparación e instalación de vidrio',0],['waterproofing','Waterproofing','Impermeabilización',1],['demolition','Demolition','Demolición',0],['property-maintenance','Property Maintenance','Mantenimiento de propiedades',0]]},
{id:'outdoor-seasonal',icon:'🌳',priority:5,label:{en:'Outdoor & Seasonal',es:'Exterior y temporada'},services:[['landscaping','Landscaping','Paisajismo',0],['lawn-mowing','Lawn Mowing','Corte de césped',0],['yard-cleanup','Yard Cleanup','Limpieza de jardín',0],['tree-service','Tree Service','Servicio de árboles',0],['sprinkler-repair','Sprinkler Repair','Reparación de riego',0],['gutter-cleaning','Gutter Cleaning','Limpieza de canaletas',0],['pressure-washing','Pressure Washing','Lavado a presión',0],['leaf-removal','Leaf Removal','Retiro de hojas',0],['snow-removal','Snow Removal','Retiro de nieve',1],['snow-plowing','Snow Plowing','Arado de nieve',1],['ice-removal','Ice Removal','Retiro de hielo',1],['storm-cleanup','Storm Cleanup','Limpieza después de tormentas',1]]},
{id:'cleaning',icon:'🧹',priority:6,label:{en:'Cleaning',es:'Limpieza'},services:[['house-cleaning','House Cleaning','Limpieza de casas',0],['deep-cleaning','Deep Cleaning','Limpieza profunda',0],['move-in-cleaning','Move-In Cleaning','Limpieza de entrada',0],['move-out-cleaning','Move-Out Cleaning','Limpieza de salida',0],['carpet-cleaning','Carpet Cleaning','Limpieza de alfombras',0],['window-cleaning','Window Cleaning','Limpieza de ventanas',0],['commercial-cleaning','Commercial Cleaning','Limpieza comercial',0],['post-construction-cleaning','Post-Construction Cleaning','Limpieza post-construcción',0]]},
{id:'moving-hauling',icon:'🚚',priority:7,label:{en:'Moving & Hauling',es:'Mudanza y transporte'},services:[['moving','Moving','Mudanza',0],['furniture-moving','Furniture Moving','Mudanza de muebles',0],['loading-unloading','Loading & Unloading','Carga y descarga',0],['furniture-delivery','Furniture Delivery','Entrega de muebles',0],['appliance-delivery','Appliance Delivery','Entrega de electrodomésticos',0],['pickup-help','Pickup-Truck Help','Ayuda con camioneta pickup',0],['junk-removal','Junk Removal','Retiro de basura y objetos',0],['hauling','Hauling','Transporte de carga',0],['local-courier','Local Courier','Mensajería local',0]]},
{id:'business-services',icon:'🏢',priority:8,label:{en:'Business Services',es:'Servicios comerciales'},services:[['commercial-cleaning','Commercial Cleaning','Limpieza comercial',0],['commercial-hvac','Commercial HVAC','HVAC comercial',1],['commercial-plumbing','Commercial Plumbing','Plomería comercial',1],['commercial-electrical','Commercial Electrical','Electricidad comercial',1],['refrigeration-repair','Commercial Refrigeration Repair','Reparación de refrigeración comercial',1],['restaurant-equipment','Restaurant Equipment Repair','Reparación de equipos de restaurante',0],['security-cameras','Security Camera Installation','Instalación de cámaras de seguridad',0],['access-control','Access Control','Control de acceso',0],['sign-repair','Sign Installation & Repair','Instalación y reparación de letreros',0],['office-maintenance','Office & Store Maintenance','Mantenimiento de oficinas y tiendas',0]]},
{id:'other-help',icon:'✨',priority:99,label:{en:'Other / I Need Help',es:'Otro / Necesito ayuda'},services:[['other','Other / I Need Help','Otro / Necesito ayuda',0]]}
].map(c=>({...c,services:c.services.map(([id,en,es,urgentCapable])=>({id,label:{en,es},urgentCapable:!!urgentCapable,categoryId:c.id}))}));
const ALL_SERVICES=SERVICE_CATALOG.flatMap(c=>c.services);
const RULES=[
['tree-service',['tree','trees','branch','branches','limb','limbs','stump','trunk','arborist','prune','pruning','trim tree','tree trimming','tree removal','fallen tree','cut tree']],
['landscaping',['landscape','landscaping','garden','mulch','plants','shrubs','bushes','yard design']],
['lawn-mowing',['lawn','grass','mow','mowing','cut grass']],
['yard-cleanup',['yard','cleanup','leaves','brush','debris','weeds']],
['sprinkler-repair',['sprinkler','irrigation','watering system']],
['gutter-cleaning',['gutter','gutters','downspout']],
['pressure-washing',['pressure wash','power wash','driveway wash','siding wash']],
['leaf-removal',['leaf','leaves','fall cleanup']],
['snow-removal',['snow','shovel','snow removal','driveway snow']],
['snow-plowing',['plow','plowing','snow plow']],
['ice-removal',['ice','icy','salt','deice']],
['storm-cleanup',['storm','storm cleanup','fallen branches','wind damage']],
['roadside-assistance',['roadside','stranded','stuck road','car help']],
['mobile-mechanic',['mechanic','engine','check engine','car repair','brake','brakes','overheating','alternator','starter','vehicle repair']],
['auto-diagnostics',['diagnostic','diagnostics','scan','check engine light']],
['auto-electrician',['car electrical','auto electrical','wiring car','battery drain']],
['tire-change',['tire','tyre','spare tire','change tire']],
['mobile-tire-service',['mobile tire','new tire','tire service']],
['flat-tire-repair',['flat','flat tire','puncture','blowout']],
['jump-start',['battery','dead battery','jump','jumpstart','jump start','car won\'t start','car wont start']],
['battery-replacement',['battery replacement','replace battery','new battery']],
['fuel-delivery',['gas','fuel','out of gas','petrol']],
['vehicle-lockout',['lockout','locked','locked out','keys','keys in car','unlock car']],
['towing',['tow','towing','tow truck','stuck vehicle']],
['windshield-repair',['windshield','glass chip','cracked windshield']],
['mobile-detailing',['detailing','car wash','detail car','clean car']],
['motorcycle-assistance',['motorcycle','bike won\'t start','motorbike']],
['handyman',['handyman','repair','fix','small repair','install','mount','maintenance']],
['plumbing',['plumb','plumber','pipe','leak','water leak','toilet','drain','faucet','sewer','sink']],
['electrical',['electric','electrical','outlet','breaker','power','wiring','switch','sparks']],
['hvac',['hvac','ac','air conditioner','heat','heater','furnace','thermostat']],
['appliance-repair',['appliance','fridge','refrigerator','washer','dryer','dishwasher','oven','stove']],
['carpenter',['carpenter','wood','cabinet','trim','shelf','shelves']],
['locksmith',['lock','locks','key','keys','locksmith','door lock','rekey']],
['garage-door',['garage','garage door','opener']],
['painting',['paint','painting','painter','walls','wall paint']],
['flooring',['floor','flooring','tile','laminate','hardwood','carpet install']],
['drywall',['drywall','sheetrock','wall hole','patch wall']],
['furniture-assembly',['assemble','assembly','ikea','furniture assembly','desk','bed frame']],
['tv-mounting',['tv','mount tv','television','wall mount']],
['smart-home',['smart home','camera doorbell','thermostat install','smart lock']],
['doors-windows',['door','window','windows','doors','screen door']],
['emergency-roadside',['emergency roadside','urgent car','road emergency']],
['emergency-mechanic',['emergency mechanic','urgent mechanic']],
['emergency-towing',['emergency tow','urgent tow']],
['emergency-plumber',['emergency plumber','burst pipe','major leak']],
['emergency-electrician',['emergency electrician','electrical emergency','sparks']],
['emergency-locksmith',['emergency locksmith','locked out house','urgent lock']],
['emergency-hvac',['emergency hvac','no heat emergency','no ac emergency']],
['water-damage',['water damage','flood','flooded','basement flood']],
['general-contractor',['contractor','remodel','renovation','construction']],
['roofing',['roof','roofing','shingles','roof leak']],
['concrete',['concrete','cement','driveway','sidewalk']],
['masonry',['masonry','brick','bricks','stone','chimney']],
['fence',['fence','fencing','gate']],
['deck',['deck','porch','patio repair']],
['insulation',['insulation','insulate','attic insulation']],
['siding',['siding','vinyl siding','outside wall']],
['windows-doors',['windows','doors','window replacement','door replacement']],
['glass',['glass','broken glass','mirror']],
['waterproofing',['waterproof','basement leak','foundation leak']],
['demolition',['demolition','demo','tear down','remove wall']],
['property-maintenance',['property maintenance','building maintenance']],
['house-cleaning',['clean','cleaning','house clean','maid']],
['deep-cleaning',['deep clean','deep cleaning']],
['move-in-cleaning',['move in clean','move-in clean']],
['move-out-cleaning',['move out clean','move-out clean']],
['carpet-cleaning',['carpet','rug','carpet cleaning']],
['window-cleaning',['window cleaning','clean windows']],
['commercial-cleaning',['commercial cleaning','office cleaning']],
['post-construction-cleaning',['post construction clean','construction cleaning']],
['moving',['move','moving','movers','boxes','relocation']],
['furniture-moving',['furniture','couch','sofa','bed','table moving']],
['loading-unloading',['loading','unloading','load','unload']],
['furniture-delivery',['furniture delivery','deliver furniture']],
['appliance-delivery',['appliance delivery','deliver appliance']],
['pickup-help',['pickup','pickup truck','truck help']],
['junk-removal',['junk','trash','garbage','haul away','debris removal']],
['hauling',['hauling','haul','transport load']],
['local-courier',['courier','delivery','local delivery','package']],
['commercial-hvac',['commercial hvac','business ac','store heat']],
['commercial-plumbing',['commercial plumbing','business plumbing']],
['commercial-electrical',['commercial electrical','business power']],
['refrigeration-repair',['refrigeration','walk in cooler','freezer','cooler repair']],
['restaurant-equipment',['restaurant equipment','oven restaurant','fryer']],
['security-cameras',['camera','cameras','security camera','surveillance']],
['access-control',['access control','badge','door access']],
['sign-repair',['sign','sign repair','store sign']],
['office-maintenance',['office maintenance','store maintenance']],
['pest-rodent-control',['pest','bug','bugs','insect','roach','cockroach','mouse','mice','rat','rats','termite','ants','bedbug','spider','wasp']],
['other',['other','help','not sure','unknown']]
];
function findServiceById(id){return ALL_SERVICES.find(s=>s.id===id)||null}
function smartMatch(text,{limit=5}={}){const q=String(text||'').trim().toLowerCase();if(!q)return[];const norm=q.replace(/[^\p{L}\p{N}]+/gu,' ').trim();const tokens=new Set(norm.split(' ').filter(w=>w.length>1));const scored=[];const singular=w=>w.length>3&&w.endsWith('s')?w.slice(0,-1):w;const close=(a,b)=>a===b||singular(a)===singular(b)||(a.length>4&&b.length>4&&(a.startsWith(b)||b.startsWith(a)));for(const [id,terms] of RULES){let score=0,matchedTerm=null;for(const term of terms){const t=String(term).toLowerCase(),tn=t.replace(/[^\p{L}\p{N}]+/gu,' ').trim(),parts=tn.split(' ').filter(Boolean);if(!tn)continue;if(norm.includes(tn)){const s=parts.length>1?.98:.9; if(s>score){score=s;matchedTerm=t}}else if(parts.length===1){for(const token of tokens)if(close(token,parts[0])){if(.84>score){score=.84;matchedTerm=t}}}else{const overlap=parts.filter(p=>[...tokens].some(token=>close(token,p))).length;if(overlap&&overlap===parts.length){const s=Math.min(.92,.68+overlap*.08);if(s>score){score=s;matchedTerm=t}}}}if(score)scored.push({service:findServiceById(id),score,matchedTerm})}for(const s of ALL_SERVICES){if(s.id==='other')continue;const words=s.label.en.toLowerCase().split(/\W+/).filter(w=>w.length>2);const n=words.filter(w=>[...tokens].some(token=>close(token,w))).length;if(n)scored.push({service:s,score:Math.min(.82,.48+n*.12),matchedTerm:null})}const seen=new Set();const out=scored.sort((a,b)=>b.score-a.score).filter(x=>x.service&&!seen.has(x.service.id)&&seen.add(x.service.id)).slice(0,limit);return out.length?out:[{service:findServiceById('other'),score:.2,matchedTerm:null}]}
function localizedLabel(item,lang='en'){return item?.label?.[lang]||item?.label?.en||''}
const api={SERVICE_CATALOG,ALL_SERVICES,findServiceById,smartMatch,localizedLabel};
if(typeof module!=='undefined'&&module.exports)module.exports=api;
if(typeof window!=='undefined')window.ZOVRO_CATALOG=api;

})();
